---
title: "PhyloPapers 2025, Growth of the tree of life"
description: "Discussion of Chen et al. (2025) about the growth of the tree of life"
author: "Brian O'Meara"
date: "09/06/2025"
citation: true
categories: [phylopapers, phylogenetics, teaching] 
---

This week I wanted students to learn more about the growth of our knowledge of the tree of life. We're reading:

> Molly Chen, Artem I. Kholodov and Laura A. Hug (2025). The evolution of the tree of life. Phil. Trans. R. Soc. B 380: 20240091.
<https://doi.org/10.1098/rstb.2024.0091>

This is a really cool paper: it took snapshots of the info in GenBank at five year intervals, built trees from the available info at each time step, and compared how the trees changed over time. It also looked at trees from key papers over time. I also liked it for class as it touched on long branch attraction and tree distances, which are useful background for students to know. The paper also generated discussion of tree construction, including use of backbone trees, as well as the need for taxonomic name resolution and massive deletion of sequences (for example, going from 2.2 million genomes down to 333K after filtering). I still remember the days of [fighting hard for every base pair](https://www.ncbi.nlm.nih.gov/portal/utils/pageresolver.fcgi?recordid=68bce924dbd3fe45a71f670a), so the shift in the genomic era to tossing most info is still viscerally painful, but useful. 

This is also a paper where the supplement has some genuinely useful info: it's available at <https://doi.org/10.6084/m9.figshare.c.7897347.v1>. 

One thing that became apparent is how many of us, myself included, have nearly all our natural history and taxonomic knowledge focused on eukaryotes. Even issues like the possible lack of monophyly of Archaea were revelations to many: the three domain view of life is often still taught as the default. I plan to read more widely to understand the diversity of life better (my secret hope is that at some point [Riley Black](https://rileyblack.net) will write a book on single-celled life as engaging as her other ones...).

I made intro slides with some of my background material and some figures from the paper: [PDF](ChenEtAl2025_EvolutionOfTheTreeOfLife.pdf) and [PowerPoint](ChenEtAl2025_EvolutionOfTheTreeOfLife.pptx).



___

To subscribe, go to <https://brianomeara.info/blog.xml> in an RSS reader.