---
layout: page
link: https://www.brianomeara.info/lab/shouldyougotogradschool/
slug: shouldyougotogradschool
title: Should you go to grad school to be a professor?
---

A key question I get from advanced level undergrads is whether they should go to grad school intending to be a professor. I also tell prospective students in my lab some of the benefits and costs of choosing this career path. Here I am compiling some of this information; note that this is my personal view.

### Pros


  * If all goes well, you get to **pursue your passion**: if you care about how anoles in Cuba feed, you can spend your life studying that; or figuring out how Ebola spreads, what conditions are required for life to evolve, etc. This is a huge benefit: very, very few humans are privileged enough to follow their passions as the core of how they make their living.

	
  * You **contribute to human knowledge**. Matt Might has a [good visual](https://matt.might.net/articles/phd-school-in-pictures/) for this. If all goes well, you bring information to humanity that we didn't know (which can include a discovery that what we thought we knew was wrong). It is pretty amazing to live a life at the boundary of knowledge and ignorance and to be one of the people pushing this boundary outward.

	
  * You **teach**. Imagine teaching an intro bio class to non-majors. This may be the last chance many of them have to learn about the reality of evolution, the causes of climate change, how bacteria evolve in response to antibiotics, how nitrogen affects the ecosystem, and more -- and it's up to you to do this well.

	
  * **Standard of living in a faculty job**: faculty aren't paid what people with their degree of training might get working on Wall Street or in Silicon Valley, but it's a solid middle class or upper middle class salary, typically in an area with good schools, health care, etc.


### Cons

	
  * **You might not get to do this**, after investing 5 years in a PhD and multiple years as a postdoc. Many people choose to do a PhD for reasons other than pursing a faculty job, and this is great. One thing we need to do better is train people for these vocations (careers in NGOs, government, industry, etc.) within PhD programs, especially since that is where many of our students choose to go. However, there is also a population (the intended audience for this post) who are planning to get a faculty job, but end up not finding one. It's not unusual to get hundreds of good applicants for an assistant professor position, but only one of them will be successful. And the reason that she or he gets the job is partly overall "quality" (things like publication record, teaching experience, ability to get grants) but it is also largely due to extrinsic factors: need to have someone to teach a particular course, someone with experience working in a certain region, etc. My department (University of Tennessee, Knoxville, Ecology and Evolutionary department) [tracks this info](https://eeb.bio.utk.edu/2015/08/11/eeb-a-great-place-for-a-phd/) for our graduates: after having their PhD for five years, 55% are tenure track faculty, 17% are in government jobs (EPA, etc.), 10% are in non tenure track research or teaching jobs, and so forth. This should give you an idea of probabilities of different outcomes (which is a mixture of choice and constraints); wherever you apply should have data like this.

	
  * **Work does not stop**. Of course, for the parts of the career that you love, this could be a good thing: it can be fun to read the literature, develop new ideas, make new observations. But you will also have to write grants (about 92% of which will fail, given NSF funding rates), deal with the business of teaching (i.e., answering questions from students that are already addressed on the syllabus), and so forth. You definitely need to take breaks and think about work-life balance, but the pressure is always to work more.

	
  * **Danger**: for work involving going to remote areas in the field, there is the real risk that you will be injured or killed. See [here](https://strangebehaviors.wordpress.com/2011/01/14/the-wall-of-the-dead/) for a list of naturalists who have died on the job. A [study (Clancy et al., 2014)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102172) found a very high number of incidences of sexual harassment and sexual assault in the field, with the victims often being trainees.

	
  * **Depression**: In a recent survey (see article about this [here](https://www.insidehighered.com/news/2015/04/22/berkeley-study-finds-high-levels-depression-among-graduate-students)), over 4 in 10 PhD students in biology at Berkeley were assessed to be depressed. Grad school and science in general can be stressful. Frequent failure is a given (rejection from journals, grants, jobs, even (in some ways, especially) for ambitious, successful scientists). You and your work will also be evaluated by peers: do you get a job, get tenure, etc. People who have a different view than yours will go after your work in the literature. This is (often) healthy for science as a whole, but it doesn't necessarily feel good. Also think about family support. If all goes well, and you're lucky, you might have your first "real" job as a professor at age 30. You are more likely to be mid thirties or older, especially if you do a masters before PhD, multiple postdocs, etc. What will your parents, partner, etc. say when you still do not have a "real" job at 35, over a decade after you "finished college"?

	
  * **Standard of living on the way up**: Grad students in many places don't get paid well. It is school, not a job, but it is also typically five years or more for a PhD in the US, and that's a long time to be living with little ability to build savings, especially at a time in people's lives when they often start having children. Postdocs are often underpaid, and have to find and get a new job, in a different part of the world, every year or two. There will also be unexpected expenses (student fees, supplies while you're in the field, travel to conferences) that might come out of your personal funds (shouldn't but might). A scary new trend at some universities is **eliminating health care plans**, including subsidies, for grad students, sometimes with mere days of notice. In addition to avoiding schools like this (unless you have the resources for health care on your own; remember your parents can only cover you until you are 26), you may want to check with schools admitting you about guarantees for health care. Note that non-US universities may have different policies.

	
  * **Moving**: how many faculty members has your current department hired since you've been there in the area you will study? Usually zero or one. If you want to work at college X, it might be 20 years or longer until there is a job opening in an area where your research would make you an appropriate candidate, and there will be 250 applicants for that job. Thus, you have to be ready to move to where a job is. Even if you have a vague geographic preference (southwestern US to be near family, say), there's a good chance you won't end up there, at least not for decades. If you are unwilling to move, a PhD in science can be a great idea, but you should definitely consider career paths outside of the faculty track once you have that PhD.

	
  * **Two-body problem**: If it's hard for one person to end up in a place she or he wants, it's even harder for two. Some places will consider spousal accommodations, but not all will (and it can depend on things like whether your spouse would fit naturally in your college), and it might be far from the ideal position for your partner. Some couples end up in long distance relationships for years.


I am personally very glad I've made this choice of career; there are bumps, but overall it has been wonderful. My goal is not to dissuade people from going to grad school, only that you are well-informed about the risks and benefits before you start. My list has more cons, but that doesn't mean they outweigh the benefits, only that I think they require more explanation: the benefits of a career in science are many and obvious to those with contact with this. Talk to current and past students, find out from the program about their outcomes, talk to faculty and postdocs at your current institution and at where you may go to grad school. Also be sure to find out about alternate careers after grad school: most faculty know best about how to make more faculty, but your passion may lie in starting a conservation organization, working with Congress to pass legislation, designing software for biology education, writing popular books about science, or a myriad of other careers that relate to biology but which do not necessarily lead to a faculty job (or even require grad school).
I strongly urge people applying to my lab to first read [**The Professor Is In**](https://theprofessorisin.com/buy-the-book/) by Karen Kelsky. It's cheap ($15 cover price, ~$8 at some retailers) and provides a good, albeit harrowing, overview of how a career with a PhD works now and what strategies will help. Some of it is tailored towards humanities rather than sciences, so check before following all its advice (i.e., getting outside teaching gigs while a grad student is _not_ a good idea for most science students), but it's a good book overall.
