---
comments: false
layout: page
link: https://www.brianomeara.info/general/
slug: general
title: General
---

Most of my website is designed for a specialized scientific audience, but it is important to include a summary for a general audience: taxpayers, colleagues outside of science, and so forth. Faculty members are responsible for teaching, research, and service; of the three, research may be the least understood (one common misconception is that professors only teach; we teach, but contributing new knowledge in addition to disseminating existing knowledge is also a major part of our jobs), so I start with that, though all are important. I also try to explain the unfamiliar parts of the job so you can get a sense of what I do. I am currently a full professor.


## Research


A major duty of a science professor, especially at a research-intensive place like U. of Tennessee, Knoxville, is to expand human knowledge through their research efforts. I work in a variety of areas to do this.




  * **Species discovery**: One area is figuring out how many species are actually present within a group. We often think of new species being discovered by, say, [an astute observer seeing a weird fish in a market](https://en.wikipedia.org/wiki/Marjorie_Courtenay-Latimer#Discovery_of_the_coelacanth), or on an expedition to a remote area of the jungle, but in fact many new species are discovered as a result of data showing that what we thought was one species was actually two different species with limited or no interbreeding: see examples of [tapirs](https://voices.nationalgeographic.com/2013/12/20/new-species-animals-tapir-brazil/) or even [African elephants](https://news.nationalgeographic.com/news/2010/12/101222-african-elephants-two-species-new-science/). I develop some of the techniques we use to make these discoveries. This matters for basic biology: it is hard for scientists to communicate information without having names for biologically meaningful groups, and it is important to understand what leads to and maintains separate groups, but it also matters in the applied area: it is hard to conserve species properly if we do not recognize what they are (we might wipe out a species that we didn't realize was independent, or might devote resources to saving a "species' that is actually just a variant of a common species and lose another species due to finite resources).


  * I also develop methods for **looking at past history of life**. For example, we have methods that can give information about how species have multiplied through time: do they exchange genes for a long time, has their population crashed at some point in the past, etc. This helps us understand how the current world came to be, but also may be useful in predicting what will happen as life and the environment continue to change.


  * One major research focus has been developing approaches for looking at **how and why traits change over time**. For example, if you look in many environments you see more flowering plants than nonflowering plants like pines and ferns -- why is this? Or questions like, once most of the dinosaurs (birds survived) went extinct, did mammals' body size rapidly increase or was it gradual?


  * One way I accomplish my research goals, as well as help others, is by **writing software**. It's one thing to have an idea of how to solve a problem, but if you write a program to do this, then you and others can actually use the method to solve a problem. My software is free and open source. This means anyone can use it without paying me money (which makes sense, as my work has already been directly or indirectly paid for by taxpayers). It also means that anyone can look inside the software to see how it works. For example, [here](https://github.com/bomeara/brownie/blob/master/brownie.cpp) is an example of some of the code I wrote as a grad student; you can see how people have used it by looking at [the hundreds of articles that cite it](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=9860338757215931909) (though some are citing just the method, not using the software itself). Another important aspect of open source software is that not only can you look at it, you can build on it to make new software, without needing my permission, as long as you make it clear that you're reusing my software, give appropriate credit, and release your software under the same rules (allowing reuse, showing the code, etc.). Building on others' work, while giving them credit, is one of the key ways science advances. Making software open also lets others check for errors and try to reproduce studies.


There are various other research topics; look [here](https://brianomeara.info/research) for more info.


### Research Funding


This research requires funding to move forward. In some ways, running a lab is like running a small business (my father cofounded and ran a small print shop, so I have seen some of what this entails). You need some money to get it off the ground for necessary equipment, people, and space. After that, potential clients have needs, and you have to make the case that you're the best group to fulfill those needs: evidence that you can make a great cake for their wedding, design a building that will get their company noticed, or reliably cut their grass twice a month. Seed funding in science typically comes from the university; at the time a faculty member is hired, there is a negotiation between the university and the candidate over what is needed for the faculty member to be successful. That money typically has to be spent down in two or three years to get the lab off the ground. After that, money comes in from clients. The typical client in my area is the US government's National Science Foundation. It puts out calls for work in particular areas: [programs to train students](https://www.nsf.gov/pubs/2015/nsf15542/nsf15542.htm), [software to take advantage of massive investments in computers and sensors](https://www.nsf.gov/pubs/2015/nsf15553/nsf15553.htm), or [data to get more information on how life has changed over time](https://www.nsf.gov/pubs/2015/nsf15520/nsf15520.htm). Hundreds of scientists turn in written proposals in response to each call, often including preliminary work to show the feasibility of their proposal. Other scientists review these proposals and evaluate them on the basis of two main criteria: intellectual merit and broader impacts. Intellectual merit is things like the importance to science of what the work will do and feasibility of the work. [Broader impacts](https://www.nsf.gov/pubs/2007/nsf07046/nsf07046.jsp) is benefit to society: improving commercial companies, providing information important for policy decisions or national security, improving the nation's infrastructure for research and education, or helping to make participants in science more representative of the country as a whole. The NSF then takes these scientists' opinions of the proposals into account, but also other considerations (making sure scientists just starting out have a chance at funds, for example), and decides which scientists get the grants. NSF requires annual reports to monitor progress; for big grants, it may do more intensive oversight (like sending scientists out to do a site visit at where the science is being done). The university typically takes about a third of each grant to cover ongoing infrastructure and other costs associated with supporting scientific research; the rest goes into equipment, travel and salaries (sometimes including salary for a professor: we typically get paid for nine months of work and can get paid out of a grant to work over the summer (which, frankly, nearly everyone does anyway, even without a grant: continuing to do experiments, write up results, mentor grad students, etc)). You can see an example of one of my funded proposals (including the broader impacts, scientific impact, and detailed budget), [here (PDF)](https://brianomeara.info/sites/default/files/OMearaNSFCAREER_2014_Pruned.pdf).
Funding is very competitive: in my areas, funding rates may be as low as 8%, meaning for every twelve grants applied for, you might get one (and some major programs limit people to no more than two grants per year, so it can take years to be successful). I have been very lucky in getting grants. For example, in one main program at NSF, the Division of Environmental Biology, [11,789 people applied for grants from 2006-2014; only a quarter got any grants](https://nsfdeb.wordpress.com/2015/04/30/deb-numbers-per-person-success-rate-in-deb/). In terms of number of grants, I was tied for 15th place out of 11,789 applicants (four grants: a dissertation improvement grant and three regular grants; I've since gotten another grant from a different part of NSF, and a CAREER grant from NSF). [This isn't a way scientists usually think about such things, by the way -- there's a large amount of luck involved in getting grants once you're in the tier of good proposals, so there's really no reason to assume that someone with three grants is doing better or more work than someone with no grants; we usually focus much more on scientific outputs (ideas, papers, software, data, students produced), which are what really matter. However, for a general audience, this measure might be more intuitive].
In addition to their main role in supporting science, these grants help Tennessee's economy; the [approximately $2.2M of funds I have been awarded](../funding/index.html) over the past six years are predicted to create about 53 jobs (using a rough estimate from [here](https://www.dot.ny.gov/recovery/jobs)). Less approximately, my funding has directly supported four scientists and their families in Knoxville, all drawn here to work on this science.


## Teaching


Of course, another major role for faculty is teaching and mentoring. I teach introductory biology courses of around 200 students covering ecology, evolution, and an overview of life's diversity. I created a mixed senior- and graduate-level course on major themes and ideas in evolution that I teach to about 30 students annually. This was inspired in part by a similar course I was lucky enough to take from Steve Gould and Dick Lewontin as an undergrad. I teach part of our introductory course for graduate students, covering why we can use phylogenetics to understand ecology and evolution and how to do so. I also teach numerous smaller seminar-style courses mostly for graduate students. Last year (Spring 2016) I taught a 235-student introductory biology course as well as created a new, online and in person graduate course in [phylogenetic methods](https://phylometh.info), where materials (exercises, videos) are free to all to use. Scientists often go around the world giving talks on their research; I do that, but I also do short workshops for training in software or methods to students in places like Brazil, Sweden, Switzerland, Ohio, North Carolina, Louisiana, and even here in Tennessee. I also talk to students in local elementary schools.
I also mentor students. Undergrads can learn to do research in my lab (given my rather theoretical work, few of our biology students have opted in to this, but there have been some notable exceptions): I help them design projects and then help them gain the skills to address them. I have four PhD students in my lab (one is coadvised with another faculty member) who get more intensive training and even more independence. Graduate students also form a committee of, in our department, typically four faculty members including their main advisor. Their committee helps advise them in aspects of their work where an outside view can be helpful and helps maintain academic standards across a program. I currently serve on approximately a third of our department's grad students' committees, as well as for students outside our department. Finally, I mentor postdocs. These are scientists who have their PhD and thus extensive research experience but who do not yet have a permanent position. Mentoring can include expanding their skill sets into a different area of biology or math, helping them put their work in a broader context, and helping them apply for faculty jobs or for jobs outside of academia. I have mentored eleven postdocs so far. Slightly more than half were funded by the National Institute for Mathematical and Biological Synthesis ([NIMBioS](https://nimbios.org)), which is housed at UT Knoxville campus (and which has [resulted](https://www.nimbios.org/about/) in over 400 scientific publications, 4900 visits from mathematicians and biologists from all over the world, and $35M of federal funding into Tennessee), and the remainder from support from my own grants or other funds.


## Service


The third part of my job is service. These are things that are key to proper functioning of a department, or serve a purpose outside of our department, but aren't directly research or teaching. For example, our department is attractive to grad students (good mentors, opportunities for important research, guaranteed support to students making adequate progress) and so we receive far more applicants than we can admit. I help decide which of these applicants we can admit, based on their application info (letters of rec, research experience, application essays, and other information) and factors in our department. Peer review is critically important in science: before getting something published (or a grant funded) other scientists in the field (in some ways, your competitors) have to volunteer their time, usually anonymously, to review your work and suggest changes before it can be published. These scientists don't get paid for this; it's just accepted as one of the duties that come with the job. It's as if Toyota couldn't start selling its new minivan until engineers at Honda, Chrysler, and Kia had finished checking it out and making recommendations about it. This can be a painful process, but it can really make the final work that gets published better. I participate as a reviewer for many scientific journals as well as funding agencies. Outreach is also a part of service; I do this through advising the student group [Darwin Day TN](https://darwindaytn.org/), maintaining an overview of [software for phylogenetics in R](https://cran.r-project.org/web/views/Phylogenetics.html), helping to organize scientific conferences, and many other activities.
