---
layout: opportunities
link: https://www.brianomeara.info/opportunities/
slug: opportunities
title: Opportunities
---

There are several kinds of opportunities for joining the lab. 

Standard lab policy is that you should reach out to [current and past lab members](https://brianomeara.info/personnel.html) for feedback on what it's like here, and **never** tell me what they say, positive or negative. That way they know they can be frank with you.

I also suggest you tell me about other things you may need -- spousal accommodations, info about child care, etc. -- only once you receive an official offer. I can try to work with you on ways to help, but this way, neither I nor anyone else involved can discriminate against you based on these factors, even unconsciously, before you get an offer.

You might look at [lab guidelines](https://brianomeara.info/guidelines.html) to get a sense of how the lab works. Materials I created for [promotion](https://brianomeara.info/promotion.html), especially the promotion packet itself ([PDF](https://brianomeara.info/files/OMearaPromotionPacket.pdf)) may give you a good summary of where my teaching, research, and service have been and are going. For what you might learn here, [learning objectives](https://brianomeara.info/learningobjectives.html) can be helpful.

Like anywhere, the Knoxville area has pros and cons, and everyone will have their own list of what things matter most to them and their family. In our conversations I'll speak honestly about what I see as some of these. Some of the pros that might not be readily apparent from afar are the natural beauty of the region (it's close to Great Smoky Mountains National Park: [photos](https://www.mysmokymountainpark.com/photos/great-smoky-mountains-photos/), [species](https://www.inaturalist.org/observations?lat=35.62384903373154&lng=-83.58458353164062&place_id=any&radius=45.24340648817372&view=species), [website](https://www.nps.gov/grsm/index.htm)); the fact of seasons (spring and fall are spectacular here); and a collaborative department. One of the downsides is the [suddenly surging housing market](https://www.wate.com/news/knoxvilles-rental-occupancy-rate-shoots-to-98-6-what-that-means-for-renters/), making rentals difficult. 

## Postdocs

I often have postdoc positions available; there are none at the moment (this page will be updated if there are some). That said, if you have a good idea and would like to work on an [NSF postdoctoral research fellowship grant](https://new.nsf.gov/funding/opportunities?sort_bef_combine=search_api_relevance_DESC&fields_selected%5Btitle%5D=title&fields_selected%5Bsubtitle%5D=subtitle&f%5B0%5D=student_educator_eligibility%3Apostdoc), please reach out. There's also a possibility of working on a grant together that will support you on soft money, but that is risky (6 months for an agency to review, low funding rates).

## Grad students

I am open to having new grad students start in my lab. The application deadline is December 1, 2023; the start is in August, 2024.  

* Students are admitted to the program, not to the lab. That means that it's not just up to me, and if you don't end up liking the first lab you join, moving is possible. You still have to have a faculty member saying, "I want them in my lab" to get in.
* Reach out to me ([email](mailto:bomeara@utk.edu)). We can talk about your interests, expectations, etc. There's also the possibility of fee waivers for applying (not really a waiver -- just that the lab will pay your fee to the graduate school). Like an [increasing number of other programs](https://www.sciencemag.org/careers/2019/05/wave-graduate-programs-drop-gre-application-requirement) that care about pulling students from a talented, diverse pool, rather than the pool who can pay to prove they know about odd numbers, parallel lines, and bar graphs ([really!](https://www.ets.org/gre/revised_general/prepare/quantitative_reasoning/)), we no longer require the GRE. 
* I can teach you about active questions in evolution, methods use and development, programming, and more. I cannot as easily make you curious and driven. Given how our graduate program and especially how my lab runs, you shouldn't expect to be handed a research topic from above -- you will develop your research topic(s) with my help and the help of your committee. I will thus ask you to propose some concrete research ideas as a filter -- it's not a commitment that you're going to work on them, but a way to see if you care about particular ideas.
* For those making adequate progress, tuition is covered, as are fees, you're in a health care plan, you get a $27K/year stipend (this has been rising over the past few years, though it still is less than the current [living wage](https://livingwage.mit.edu/metros/28940) for Knoxville, TN, of $32,385). In exchange, you're expected to TA every semester (but not summer) -- the TA time load is ~20 hours per week. The stipend is paid out over all 12 months. Students also can apply for research funds (most students receive them, but in varying amounts) and of course there are other grants as well. 
* Grad school is a path to many careers: governmental agencies, private companies, NGOs, academia, and more. I will try to support you in whatever career you feel is best for you (and this can change during your time in grad school), and your intended career plays no role in whether I want you in the lab or not. Do note that, like most academics, my training and professional contacts are generally in academia, but that does not mean I won't be able to help with other careers.
* Grad school, especially for people with the intention of ending up in a tenure track job, has benefits and costs that not all people applying may know about. I have a [page](https://brianomeara.info/shouldyougotogradschool.html) on this -- please read it before choosing this path.
* Matt Might has a good [visual guide](https://matt.might.net/articles/phd-school-in-pictures/) of what it means to get a PhD (though Masters is similar; in our field, it's ~1/3 of the research effort, but still represents a contribution to knowledge).
* Risk factors: If you move somewhere to work with someone, it's nice to know they'll remain there. Folks do move around in science, but I have no imminent plans to do so. I try to run my lab very transparently, so if I do start considering a move (to a different institution or into administration), I will let lab members know (unless they don't want to be told until it's a sure thing to reduce stress). 
* For admissions, our department considers student "quality" (nebulous: things like research experience and having a good research question help), overall balance (don't want to admit only people working on birds one year), and priority of faculty. Pre-tenure faculty have highest priority along with people with grant funding who need to find students for their grants; after that, it's largely based on how many students are GTA-supported in a faculty member's lab. I have one student who will be graduating Fall, 2023, so I should be competitive in the second pool for people applying to start in August, 2024.

For application information, go to <https://eeb.utk.edu/graduate-studies/application-information/>. There is information at a university level for applying at <https://gradschool.utk.edu/admissions/applying-to-graduate-school/>. Students from countries outside the US are more than welcome. See <https://gradschool.utk.edu/admissions/applying-to-graduate-school/admissions-for-international-students/> for more information (remember our department deadline of Dec. 1, which is earlier than the university deadline). Our [international office](https://international.utk.edu/) can help with visas and other information (and students who have worked with this office generally find it helpful). Also note that United States national policy affects visas and related paperwork, and so what is required and permissible may change.

## Undergrads

There are no entry level jobs in the lab: there are no turtles to feed, beakers to clean, seeds to count. Instead, I typically work with students to develop research questions they care about (past ones have included Slavic language evolution and evolution of salamander development). It is like a graduate student dissertation, just shorter and perhaps more accessible. So if you have some question you're curious about, even if it's vague ("I really like speciation", "Phylogenetic trees are awesome"), email me to set up a time we can talk. We can typically arrange for you to receive research credit for the research you are doing. The earlier you do this, the better -- it gives you time to learn more skills to better answer your questions and really consider the biology.
