

## Mentoring, Postdocs

I have mentored numerous postdocs off of my own grants and/or as one of their chosen NIMBioS mentors. Note that NIMBioS postdocs pursue independent research projects but choose one faculty member to mentor them in math and another to mentor them in biology (I have served in both roles).


|Name                                                                             |Duration     |NIMBioS |Current Position                                                |
|:--------------------------------------------------------------------------------|:------------|:-------|:---------------------------------------------------------------|
|[Hugo Alamillo](https://people.northseattle.edu/users/halamillo)                 |2011-2012    |N       |Assistant Professor at North Seattle College                    |
|[Barb Banbury](https://www.linkedin.com/in/bbanbury)                             |2010-2012    |N       |Statistical Analyst at Fred Hutch                               |
|[David Bapst](https://geogeo.tamu.edu/people/profiles/faculty/bapstdavidwilliam.html)  |2017-2019    |N       |Instructional Assistant Professor at Texas A&M             |
|[Jeremy Beaulieu](https://www.jeremybeaulieu.org/)                                |2012-2016    |Both    |Associate Professor at U. of Arkansas                           |
|[James Boyko](https://jamesboyko.com/)                                |2022-present   |N    |Current lab postdoc                           |
|[Juanjuan (JJ) Crosskey (formerly Chai)](https://www.linkedin.com/in/jjcrosskey) |2011-2013    |Y       |Quantitative Analyst at Quantamental Technologies LLC           |
|[Dominic Evangelista](https://www.roachbrain.com)                                |2018-2018    |Y       |Assistant Professor at Adelphi U                                 |
|[Nathan Jackson](https://nathandjackson.com/)                                     |2013-2016    |N       |Researcher at National Jewish Health                            |
|[Tony Jhwueng](https://www.tonyjhwueng.info/)                                     |2009-2011    |Y       |Associate Professor Feng-Chia U., Taiwan                        |
|[Sandy Kawano](https://sandykawano.weebly.com/)                                   |2014-2016    |Y       |Assistant Professor at George Washington U |
|[Michelle Lawing](https://people.tamu.edu/~alawing/)                              |2012-2014    |Y       |Assistant Professor at Texas A&M                                   |
|[Ryan Martin](https://www.martinevolutionaryecologylab.com)                       |2012-2013    |Y       |Assistant Professor at Case Western U                              |
|[Nick Matzke](https://nickmatzke.weebly.com)                                      |2013-2015    |Y       |DECRA Fellow at The Australian National University in Canberra  |
|[Megan Rua](https://meganrua.wordpress.com)                                      |2015-2016    |Y       |Assistant Professor Wright State U                              |
|[Luna Sanchez Reyes](https://www.lunasare.com/)                                  |2017-2019    |N       |Postdoc in Emily McTavish's lab           |
|[Sergei Tarasov](https://www.tarasovlab.com/)                |2016-2018    |Y       |Coleoptera Curator at Finish Museum of Natural History    |
|[Jodie Wiggins](https://jwiggi18.github.io/)                                     |2018-2019    |N       |Teaching Assistant Professor, Oklahoma State U                  |


## Mentoring, Grad students in my lab

 


|Name                                                                      |Stage       |Time in Lab  |Note                           |
|:-------------------------------------------------------------------------|:-----------|:------------|:------------------------------|
|[Sam Borstein](https://fish4thought.wordpress.com/)                       |PhD student |2014-2019    |                               |
|[Jenn Bosco](https://sites.google.com/site/jenniferboscoinfo/home)        |PhD student |2012-2017    |Co-advised with Susan Riechert |
|[Krista De Cooke](https://www.linkedin.com/in/krista-de-cooke-163a87116/) |PhD student |2020-present |Co-advised with Dan Simberloff |
|[Katie Massana](https://sites.google.com/site/kathrynamassana/home)       |PhD student |2012-2017    |                               |
|[Orlando Schwery](https://sites.google.com/site/orlandoschwery/home)      |PhD student |2014-2020    |                               |
|[Jenn Summers](https://cubalibrejenn.wixsite.com/jennsummers)             |PhD student |2020-2021 |                               |


## Mentoring, Undergrad students in my lab

 


|Name                                                                      |Stage     |Time in Lab |Note |
|:-------------------------------------------------------------------------|:---------|:-----------|:----|
|Tyler-Christian Daniels                                                   |Undergrad |2019-2020   |     |
|Stephen Ray                                                               |Undergrad |2019-2020   |     |
|Zach Tharpe                                                               |Undergrad |2019-2020   |     |
|[Christian Yarber](https://www.researchgate.net/profile/Christian_Yarber) |Undergrad |2015-2016   |     |
|[John Anderson](https://sites.google.com/view/john-anderson-research)	   |Undergrad |2021-present   |     |


## Mentoring, Grad student committees

In addition to my own students, of course.


|Name                     |Department   |
|:------------------------|:------------|
|Will Atwood              |Geology      |
|Jen Bauer                |Geology      |
|James Boyko              |U Arkansas   |
|Sharon Clemmensen        |EEB          |
|Troy Fadiga              |Geology      |
|Aaron Floden             |EEB          |
|Nicholas Gladstone       |Geology      |
|Mauricio Gonzalez-Forero |EEB          |
|Alannie-Grace Grant      |EEB          |
|Phillip Hollingsworth    |EEB          |
|Whitaker Hoskins         |EEB          |
|Will Howell              |EEB          |
|Ivan Juric               |EEB          |
|Cedric Landerer          |EEB          |
|Jasper Lee               |Microbiology |
|Sara Lipshutz            |EEB          |
|Bryan Looney             |EEB          |
|Liam Mueller             |EEB          |
|Tyson Paulson            |EEB          |
|Todd Pierson             |EEB          |
|Ryan Rooney              |Geology      |
|Max Rupp                 |EEB          |
|Geetha Saarunya S        |GST          |
|Leonidas Salichos        |Vanderbilt   |
|Marisol Sanchez-Garcia   |EEB          |
|Sarah Sheffield          |Geology      |
|Jordan Utley             |GST          |
|Jess Welch               |EEB          |
|Rachel Wooliver          |EEB          |


## Mentoring, Faculty

Our department now has faculty mentored by a committee of later career faculty. I have served on committees for folks hired after me.


|Name                                                          |Department |
|:-------------------------------------------------------------|:----------|
|[Liz Derryberry](https://derryberrylab.wordpress.com/people/) |EEB        |
|[Stephanie Kivlin](https://skivlin.wordpress.com/)            |EEB        |
|[Kimberly Sheldon](https://www.biogeographyresearch.org/)      |EEB        |
