---
title: "Tenure and promotion letters"
description: "How I write promotion and tenure letters and what factors we should examine"
author: "Brian O'Meara"
date: "06/18/2026"
citation: true
categories: [service, letters, tenure] 
---

In US academia, it's common to have external evaluators write letters for faculty seeking to get tenure (a mechanism for maintaining academic freedom, to ensure someone can't be fired for their research, teaching, or service work, while still allowing dismissal for misconduct or other causes) or promotion (moving up one academic rank, often assistant to associate professor or associate to full professor). Even within a discipline like biology, there are subfields, and it can be hard to assess the true impact of someone's work if you are not in the subfield. For example, for people working on describing and revising species and other taxonomic groups, good work is adopted by other taxonomists, reflects careful examination of the evidence, vouchers are deposited in multiple collections, and so forth, but it will not generate a lot of citations immediately but will be cited for decades; on the other hand, a new software tool in phylogenetic methods might get highly cited for a few years but then be supplanted by a better tool or even a new version of the same. 

## Steps to gathering information

When I write letters, I usually go through the following steps first:

* Read the unit's standards for promotion and/or tenure: it's basically the rubric the department and those above them will use, so it is worth keeping in mind when reading the candidate's materials to find relevant points. Often, external reviewers are asked to assess research and maybe service -- we generally don't have enough evidence to comment on teaching.
* Read the candidate's packet. This includes the CV (papers, chapters, service, etc.) as well as essays describing their research approach and history, teaching philosophy, and so forth. Some places have candidates include a handful of key papers (more should do this!): I read all of those, too.
* Read thoroughly several of the candidate's papers. I prioritize recent papers (and only those within the review window), especially with the candidate as the first or senior author. I will also look at papers in "high profile" journals, even if the candidate was an intermediate author, as well as potentially unusual or key papers ("this person mostly studies beetles, but also had a key paper about field safety"). For most candidates I'll read all their papers in the review period; for ones with many papers in the period (~20+) I'll read the ones outlined above and look over the rest. I do not use AI to summarize the papers (or in ANY part of the process; more below).
* Look at other products or efforts (either indicated by the candidate or things I would expect from their publications -- I don't search online for whether their instagram has a lot of views, for example, but I will see if they share data from publications). Do they have software? A key for species? Outreach materials they chose to highlight? Deposited, public datasets? Effective actions to improve our field, including creating conditions for more people to thrive in it? These can become other points of strengths to highlight in the letter or potential issues ("they make great phylogenetic trees; unfortunately, they are not shared as supplemental materials or in any tree or data repositories, limiting their impact"; "their youtube channel on how samples are collected in the canopy has thousands of views, which shows their work reaches an audience").
* Consider their record of mentorship: do they have undergrads coauthoring papers? Do their grad students and postdocs seem successful (publishing papers or other products, moving on to other opportunities, etc.)? Given disparities in opportunities across institutions and utility of students across fields, there's no set standard I'm trying to look for, it's more finding other sources of strength to highlight if possible. My goal isn't for everyone I review to receive the promotion they seek (there are definitely cases where tenure isn't warranted, for example), but I do want to help make sure things are not overlooked. Also, as an external reviewer, I can't be sure an absence ("they mentored zero undergrads?!") is not just due to lack of information available ("I mentor five undergrads a semester, but, like, of course I do, why would I list it?"), while a presence is more certain.
* Think about any special circumstances they may have chosen to include -- for example, how covid may have impacted what work they could do. 

## On metrics

We like measuring things in science. Especially for something as squishy as judging people, it can feel fairer to throw numbers into a letter: Google scholar citation counts, h-index, number of papers published, impact factor of journals the candidate publishes in, and funding amounts. I love numbers, and I'm good at gathering them, but I hate the role of them in rating colleagues. First, we know there are lots of biases that come into all this: who gets cited, who gets invited to write review papers, who gets funding, etc. can depend on many factors apart from the quality of the science itself: a lot can be based on social connections, biases towards or against people with certain characteristics, preferences for certain institutions, etc. As perhaps a non-controversial example, I would expect a person in Hawaii will have fewer invited departmental seminars on their CV than the same person would if they were based out of Connecticut: all the colleges in RI, MA, NY, etc. could have a budget to have the Connecticut person drive out one day for a seminar, but might not be able to swing a plane ticket from Hawaii. Moreover, what could be a one day trip for the Connecticut person might be three days for the Hawaii person, making it much harder to say yes to giving a seminar if they have to balance child care, teaching duties, or even feeding their goldfish. That is just one example, but there are lots of examples showing MANY other social biases that can affect numbers. Moreover, our job as external experts is to evaluate the work and bring our expertise to the assessments, not just feed easily downloaded numbers that the department can already use if they choose to.

I have seen funding lead to a lot of anxiety for tenure and promotion and be used in various ways. "I need a big grant before going up"; "We expect you to make back your startup"; "This person is a rock star, they've gotten $_M as an assistant professor." Money does matter a lot. At its most basic, science requires *people*, and people require food, shelter, healthcare, etc. Grants have historically been an important way to get those in the US, and it is important to keep this funding stream robust.

However, especially on an individual level, grants are a **tool**, not a metric. Science faculty are hired to do research and teach: funding can and does help with this, but so does DNA sequencing, trips to the field, photographs, and more. Imagine how warped our discipline would become if "miles flown by the research group" became a metric we evaluate for tenure. You could craft an argument for it (it's a way of summarizing all the travel one does for communicating one's science, can indicate bringing undergrads for a transformative experience in a biome different from their local one, can correlate with gathering specimens or looking at existing collections, it's a way of helping colleagues in Hawaii finally beat ones in Connecticut, it makes the jet fuel company CEO on the board of trustees happier, etc.). But it would lead to predictable, harmful actions: spending more time jetting around than is optimal for the actual science goals; never, ever taking a direct flight (or a train); choosing field sites further away; etc. People will still vary in their ability to maximize these, so there will be variation to select on, and it's not completely unrelated to the things we actually value, but science would be healhier without this metric. In some ways, funding is similar. It can correlate with ability to do good work (which can often be expensive), it can lead to more opportunities and more people trained. But it's not the goal, it's a tool.

This is even more of the case now given changes in the US funding situation. For example, in [January 2026](https://content.govdelivery.com/accounts/USNSF/bulletins/4005589), NSF promised that it will "post broad funding opportunities for SBE [Social, Behavioral, and Economic] sciences that will accept proposals at any time" and pointed to past successes under that program, including two new recent Nobel prize winnners funded by NSF SBE. By April 2026, there were [concerns](https://apsanet.org/wp-content/uploads/2026/04/FINAL-Dissolution-of-SBE.pdf) about the elimination of the relevant directorate and *all* funding in this area, and Grant Witness shows [very few grants](https://grant-witness.us/funding_curves_nsf.html) in this area (as of June 2026). Going forward, faculty in this area may have fewer opportunities for funding, which will affect the research they can do. Using "did not get enough money" as a criterion adds harm -- if they're still managing to do substantial work despite the lack of funding, if anything being successful on a tight budget is even more impressive. The more we can focus on the work itself and not metrics like money, the more people can focus on doing impactful work. 

However, it's still a fact that others in the tenure process are going to look at things like funding. To try to put some context into the record, I now include sections like the following in all my letters (anonymized, from an actual letter):

> "It is common in promotion and tenure letters to comment on metrics. Citations is one metric, though it varies dramatically by field: a taxonomic revision of a plant genus might be critical for future researchers and receive a slow trickle of citations for the next fifty years, while a new software package might get a burst of citations that quickly taper off. For his area of research, Dr. NAME is well cited, and not just from a few high-profile publications. Similarly, grant funding is often used as a metric, even though grants are just a tool for the science, not a goal in themselves. They are also an increasingly unpredictable and rare thing to get: as I write this letter, across all institutions in STATE only XX NSF grants have been awarded in 2026. Dr. NAME's research record is strong, showing he gets adequate funding for successful research; the fact that the money to his institutions from his work is $X.XM should satisfy any unwritten criterion for amount of funding for promotion to full, let alone tenure."

I'm not sure if this actually has any effect, especially on others evaluating people in the process, but I try. 

## The letters themselves

The letters often start with how I know, or know of, the candidate. To prevent conflicts of interest they're usually not coauthors (and if so, it's usually on a massive multi-author paper) but I'll try to disclose past contact or interactions. Depending on the requirements for the university I'll include my background (they sometimes want you to demonstrate your expertise). Then I'll go into the candidate's research in general. I'll discuss fully some of the papers of theirs I think are most relevant, putting in context why they matter and how they have affected or are expected to affect the field, usually a paragraph per paper. This is where our role as tenure letter writers is most important. It's not "this was cited 15 times, yay" but being able to put in context, to people in related fields in biology and even those even more broadly, higher up in the tenure approval process, whether and how this work has an impact. I'll also highlight unusual other aspects that are in scope: for example, has does this person run a lot of workshops compared to most people in the field, do they never appear as a lead or senior author, is their software well maintained, etc. I will also discuss whether their service as indicated in their packet is commensurate with expectations in their bylaws.

## Overall

The part of science I hate the most is judging people. Reviewing papers or grant proposals is hard, but at least that's a concrete item to assess, not the authors themselves: reviewing people for tenure, grad admissions, hiring, etc. is evaluating a large part of someone's professional identity (which is not close to the full person, but it does reflect their professional output for years). And the stakes are very high: for a tenure decision, it results in either a (generally) stable job or being fired, for example. I think it's important to do, though, especially if one tries to do it in a humane way, aware of some of the harmful preconceptions we as people can bring to the process. There are also situations where failure to get enough tenure or promotion writers can lead to someone not being allowed to go up. So it's a good thing to do, so I usually say yes, but it is a substantial effort in many ways. It makes me grateful for the people who wrote promotion and tenure letters for me.  
___

To subscribe, go to <https://brianomeara.info/blog.xml> in an RSS reader.