---
title: "Fraction of history"
description: "Figure out what fraction of history you have lived through"
author: "Brian O'Meara"
date: "09/01/2023"
citation: true
categories: [history, mastodon] 
draft: false
include-in-header:
  file: functions.js
---

On mastodon, [Marius Gunderen](https://mastodon.social/@gundersen), [posted](https://mastodon.social/@gundersen/110972549747804838):

"It's wild to think about how short human history is. For example, the iron age started approximately 1200BC, which means that if you are 32 years old you have been alive for 1% of the time humans have used iron. If you are 54 years old then you have lived through 1% of horses being domesticated, the wheel being used for transport, written language and living in towns."

I thought it would be interesting educationally to do this with many events. Enter a human age in years below to do this, then click somewhere outside the box:


<form>
Age in years: <input type="text" id="age" value="44" onChange="convert_age()"><br>
</form>

<br />

<h3>Been alive for what percentage of time since:</h3>


* Domestication of corn (6700 BCE): <span id = "corn"></span>%
* Start of the iron age (1200 BCE): <span id = "iron"></span>%
* Gutenberg printing press (1400 CE): <span id = "printing"></span>%
* First usable light bulb (1879): <span id = "lightbulb"></span>%
* First flight (1903): <span id = "flight"></span>%
* US women right to vote (1920): <span id = "womenvote"></span>%
* Discovery of the structure of DNA (1953): <span id = "dna"></span>%
* US banning of segregation (1964): <span id = "segregation"></span>%
* Widespread scientific acceptance of plate tectonics (1965): <span id = "platetectonics"></span>%
* First email (1971): <span id = "email"></span>%
* US discrimination in lending banned (1974): <span id = "credit"></span>%


___

To subscribe, go to <https://brianomeara.info/blog.xml>