---
author: brianomeara_ra6153
comments: false
date: 2017-02-20 18:25:15+00:00
layout: page
link: http://www.brianomeara.info/lab/postdoc/
slug: postdoc
title: Postdoc Opportunities
wordpress_id: 661
---

I am currently seeking a postdoc for NSF-funded work for the [Phylotastic](http://phylotastic.org) project. The goal of this project is to make the tree of life more accessible for everyone. Work includes a portal for getting trees for a set of taxa from a list or a webpage, an R package for various ways to get dated trees, and more. The goal for the postdoc is to extend this work in useful ways: it could be better ways to have trees used in classrooms, more robust ways to date trees, more ways to have scientists access trees, and more -- this will be a conversation with the postdoc over what topics will work out best overall. My lab is based in Knoxville, TN, an area rich in natural beauty and affordability. However, working remotely is possible for candidates with the demonstrated ability to do so successfully: out of four lab-affliated postdocs currently, two work from Knoxville, one works from France, and one works from Texas. Out of 15 [postdocs](http://brianomeara.info/people/) I have mentored directly through my lab or as one of their National Institute for Mathematical and Biological Synthesis (NIMBioS) mentors, seven have chosen to go onto tenure track faculty positions, two are working in health research positions, and five are currently postdocs. I strive to create a welcoming and diverse environment.  Research in the lab ranges from empirical work on plant diversification to quantitative trait evolution models to models of protein evolution.
Applications should be emailed to [bomeara@utk.edu](mailto:bomeara@utk.edu) and should include
1) A cover letter (include expected completion date of PhD, if appropriate, as well as relevant skills)
2) A CV
3) A short research statement
4) Contact information for two references
5) Link(s) to repositories with examples of code you have written or attachments including such code.
Please feel free to contact me with questions before formally applying.
Experience in programming is strongly preferred; experience in R is desired, but not required. If in doubt, apply: please do not self-select yourself out from what might be a mutually beneficial position.
Review of applications will continue until filled. Presubmission inquiries are encouraged.
All qualified applicants will receive equal consideration for employment and admissions without regard to race, color, national origin, religion, sex, pregnancy, marital status, sexual orientation, gender identity, age, physical or mental disability, or covered veteran status.
Eligibility and other terms and conditions of employment benefits at The University of Tennessee are governed by laws and regulations of the State of Tennessee, and this non-discrimination statement is intended to be consistent with those laws and regulations.
In accordance with the requirements of Title VI of the Civil Rights Act of 1964, Title IX of the Education Amendments of 1972, Section 504 of the Rehabilitation Act of 1973, and the Americans with Disabilities Act of 1990, The University of Tennessee affirmatively states that it does not discriminate on the basis of race, sex, or disability in its education programs and activities, and this policy extends to employment by the University.
Inquiries and charges of violation of Title VI (race, color, national origin), Title IX (sex), Section 504 (disability), ADA (disability), Age Discrimination in Employment Act (age), sexualorientation, or veteran status should be directed to the Office of Equity and Diversity (OED), 1840 Melrose Avenue, Knoxville, TN 37996-3560, telephone [(865) 974-2498](tel:(865)%20974-2498) (V/TTY available) or 974-2440. Requests for accommodation of a disability should be directed to the ADA Coordinator at the Office of Equity and Diversity.
