---
title: "PhyloPapers 2025, Summary"
description: "Links to all sessions for the class"
author: "Brian O'Meara"
date: "12/01/2025"
citation: true
categories: [phylopapers, phylogenetics, teaching] 
---

Class is finished! A mixture of grad students, postdocs, and faculty attended the sessions. Students taking it for credit were asked on the eve of each class:

* What was the discovery or innovation in this paper?
* How this was supported by evidence in the paper?
* What didn't you understand about the paper, the methods, the questions, and/or the organisms?

I would use this info to tune what I covered in the intro for each class session. People brought a range of experience to the class, and I wanted to structure it so that everyone would learn a bit within each class session. Below are links to the posts for each week's reading (slides, reflections on the paper, etc.):

* **Tree building** ([Aug 22, 2025](https://brianomeara.info/posts/phylopapers_2025_Aug_22/)): Alison R. Irwin, Nicholas W. Roberts, Ellen E. Strong, Yasunori Kano, Daniel I. Speiser, Elizabeth M. Harper, and Suzanne T. Williams. 2025. “Evolution of Large Eyes in Stromboidea (Gastropoda): Impact of Photic Environment and Life History Traits” *Systematic Biology* 74(2):301–322. <https://doi.org/10.1093/sysbio/syae063>
* **Bayesian analysis & fossilized birth death models** ([Aug 29, 2025](https://brianomeara.info/posts/phylopapers_2025_Aug_29/)): Laura P. A. Mulvey, Mark C. Nikolic, Bethany J. Allen, Tracy A. Heath and Rachel C. M. Warnock. 2025. "From fossils to phylogenies: exploring the integration of paleontological data into Bayesian phylogenetic inference" *Paleobiology* 51, 214–236. <https://doi.org/10.1017/pab.2024.47>
* **Growth of the tree of life** ([Sep 05, 2025](https://brianomeara.info/posts/phylopapers_2025_Sep_05/)): Molly Chen, Artem I. Kholodov and Laura A. Hug (2025). "The evolution of the tree of life" *Phil. Trans. R. Soc. B* 380: 20240091. <https://doi.org/10.1098/rstb.2024.0091>
* **Genomic species delimitation** ([Sep 12, 2025](https://brianomeara.info/posts/phylopapers_2025_Sep_12/)): Sonal Singhal, Adam D. Leaché, Matthew K. Fujita, Carlos Daniel Cadena, and Felipe Zapata. 2025. “A Genomic Perspective on Species Delimitation” *Annu. Rev. Ecol. Evol. Syst.* 2025. 56:467–89 <https://doi.org/10.1146/annurev-ecolsys-102723-055311>
* **Phylogeography** ([Sep 17, 2025](https://brianomeara.info/posts/phylopapers_2025_Sep_17/)): Manica Balant^1^, Daniel Vitales^1^, Zhiqiang Wang^1^, Zoltán Barina, Lin Fu, Tiangang Gao, Teresa Garnatje, Airy Gras, Muhammad Qasim Hayat, Marine Oganesian, Jaume Pellicer, Seyed A. Salami, Alexey P. Seregin, Nina Stepanyan-Gandilyan, Nusrat Sultana, Shagdar Tsooj, Magsar Urgamal, Joan Vallès, Robin van Velzen, Lisa Pokorny. 2025. “Integrating target capture with whole genome sequencing of recent and natural history collections to explain the phylogeography of wild-growing and cultivated *Cannabis*” *Plants People Planet*. 1-18. <https://doi.org/10.1002/ppp3.70043> [^1^ = equal contributions]
* **Simulation** ([Sep 24, 2025](https://brianomeara.info/posts/phylopapers_2025_Sep_24/)): Ornela N. Dehayem, Ryan F. A. Brewer, Luis Valente, Frederic Lens, Rampal S. Etienne. 2025. “Impact of sampling strategy on inference of community assembly processes in phylogenetic island biogeography” *Methods in Ecology and Evolution*. 16:1507–1520. <https://doi.org/10.1111/2041-210X.70058>
* **Behavior and genomics** ([Oct 3, 2025](https://brianomeara.info/posts/phylopapers_2025_Oct_03/)): Sara E. Lipshutz, Mark S. Hibbins, Alexandra B. Bentz, Aaron M. Buechlein, Tara A. Empson, Elizabeth M. George, Mark E. Hauber, Douglas B. Rusch, Wendy M. Schelsky, Quinn K. Thomas, Samuel J. Torneo, Abbigail M. Turner, Sarah E. Wolf, Mary J. Woodruff, Matthew W. Hahn & Kimberly A. Rosvall. 2025. “Repeated behavioural evolution is associated with convergence of gene expression in cavity-nesting songbirds” *Nature Ecology & Evolution*. <https://doi.org/10.1038/s41559-025-02675-x>
* **Reticulate evolution** ([Oct 10, 2025](https://brianomeara.info/posts/phylopapers_2025_Oct_10/)): Gil Yardeni, Michael H. J. Barfuss, Walter Till, Matthew R. Thornton, Clara Groot Crego, Christian Lexer, Thibault Leroy and Ovidiu Paun. 2025. “The Explosive Radiation of the Neotropical *Tillandsia* Subgenus *Tillandsia* (Bromeliaceae) Has Been Accompanied by Pervasive Hybridization” *Systematic Biology* <https://doi.org/10.1093/sysbio/syaf039>
* **Trait evolution** ([Oct 17, 2025](https://brianomeara.info/posts/phylopapers_2025_Oct_17/)): Verónica A. Rincón-Rubio, Rosana Zenil-Ferguson, Alejandro Gonzalez-Voyer. 2025. “The macroevolutionary consequences of the association between frugivory and carotenoid-dependent plumage coloration in passerine birds” *Evolution*, 2025, 79(8), 1643–1657 <https://doi.org/10.1093/evolut/qpaf105>
* **Handling data deficiency in SDMs** ([Oct 24, 2025](https://brianomeara.info/posts/phylopapers_2025_Oct_24/)): Shubhi Sharma, Kevin Winner, Laura J. Pollock, James T. Thorson, Jussi Mäkinen, Cory Merow, Eric J. Pedersen, Kalkidan F. Chefira, Julia M. Portmann, Fabiola Iannarilli, Sara Beery, Riccardo De Lutio, Walter Jetz, 2025. "No species left behind: borrowing strength to map data-deficient species" *Trends in Ecology & Evolution* 40, 699–711. <https://doi.org/10.1016/j.tree.2025.04.010>
* **Machine learning for traits** ([Oct 31, 2025](https://brianomeara.info/posts/phylopapers_2025_Oct_31/)): Roberta Hunt, José L. Reyes-Hernández, Josh Jenkins Shaw, Alexey Solodovnikov, Kim Steenstrup Pedersen. 2025. “Integrating Deep Learning Derived Morphological Traits and Molecular Data for Total-Evidence Phylogenetics.” *Systematic Biology* 74(3): 453-468 <https://doi.org/10.1093/sysbio/syae072>
* **Alpha taxonomy and UCEs** ([Nov 7, 2025](https://brianomeara.info/posts/phylopapers_2025_Nov_7/)): Emma E. Jochim, James Starrett, Hanna R. Briggs, Jason E. Bond. 2025. “Speciation Pattern and Process in the California Coastal Dune Endemic Trapdoor Spider *Aptostichus simus* (Mygalomorphae: Euctenizidae) and Description of a New Cryptic Species” *Ecology and Evolution* 15:e72346 <https://doi.org/10.1002/ece3.72346>
* **Multivariate traits** ([Nov 14, 2025](https://brianomeara.info/posts/phylopapers_2025_Nov_14/)): Emma Sherratt, Jenna Crowe-Riddell, Alessandro Palci, Ammresh, Mark N. Hutchinson, Michael S.Y. Lee, Kate L. Sanders. 2025. “Rapid evolution and cranial morphospace expansion during the terrestrial to marine transition in elapid snakes” *Evolution* 1–13 <https://doi.org/10.1093/evolut/qpaf180>
* **Phylogenomics, recombination desert, and speciation** ([Nov 21, 2025](https://brianomeara.info/posts/phylopapers_2025_Nov_21/)): Nicole M. Foley, Richard G. Rasulis, Zoya Wani, Mayra N. Mendoza Cerna, Henrique V. Figueiró, Klaus Peter Koepfli, Terje Raudsepp & William J. Murphy. 2025. “An ancient recombination desert is a speciation supergene in placental mammals” *Nature* <https://doi.org/10.1038/s41586-025-09740-2>

Each week I'd decide on a topic, then look on [OpenAlex](https://openalex.org), [Google Scholar](https://scholar.google.com), and sometimes various journal websites for recent (only 2025) papers relevant to the topic. I would then read through these to find a paper that I thought would be useful for teaching, including whether I thought it was a good example of what to do (all papers have compromises, but I think students learn more from "good" papers than from ripping apart "bad" papers). I chose not to limit the papers only to ones in [DAFNEE](https://dafnee.isem-evolution.fr) journals or only papers that are open access. There are issues with the publishing ecosystem, but for this class using that to limit papers would have resulted in too small a pool of papers this semester.

___

To subscribe, go to <https://brianomeara.info/blog.xml> in an RSS reader.