---
author: brianomeara_ra6153
comments: false
date: 2014-08-01 04:00:50+00:00
layout: post
link: http://www.brianomeara.info/2014/08/01/grad-core-phylogenetics-2014/
slug: grad-core-phylogenetics-2014
title: Grad Core Phylogenetics 2014
wordpress_id: 85
categories:
- Grad Core
---

UTK EEB requires new graduate students to take an intensive team-taught course covering ecology and evolution. I present the phylogenetics portion (tree creation and tree use).
**Note the [anonymous feedback form](http://www.brianomeara.info/feedback)**: Suggest changes while it can still help you in class.


## Fall 2014:


This year I am teaching the entire phylogenetics portion. Here is the syllabus ([PDF](http://brianomeara.info/sites/default/files/eeb_511_core_2014_syll.pdf)) and lectures are below; the recorded videos are [here](http://www.youtube.com/playlist?list=PLGSdJRFzICcNgNPD1n5rGbySidMpy7Zqo).




  1. Intro to phylo ([PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics1OMeara.pdf)), [R exercise](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_OMeara_BasicPhylo.R)


  2. Likelihood, Bayes, model selection, bootstrap. ([PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics2OMeara.pdf)), [R exercise](http://brianomeara.info/sites/default/files/BayesVsMLExercise.R), [R exercise answers](http://brianomeara.info/sites/default/files/BayesVsMLExerciseAnswers.R) Background reading: [Lewis 2001](http://hydrodictyon.eeb.uconn.edu/people/plewis/pdfs/Lewis_2001-TREE-16-1.30-37.pdf)


  3. Ingredients for phylogenetic methods. [PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics3OMeara.pdf). Background reading: [O'Meara 2012](http://www.annualreviews.org/doi/pdf/10.1146/annurev-ecolsys-110411-160331)


  4. DNA models, heterogeneity, alignment ([PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics4OMeara.pdf)). [Mesquite](http://mesquiteproject.org), [Tracy Heath's](http://phyloworks.org) [Beast Tutorial](http://treethinkers.org/divergence-time-estimation-using-beast/)


  5. Continuous traits and tree stretching ([PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics5OMeara_Strech.pdf)). [R script](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_OMeara_ContinuousExample.R)


  6. Gene tree incongruence. Background reading: [Maddison 1997](http://sysbio.oxfordjournals.org/content/46/3/523.full.pdf+html) [PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics6OMeara.pdf)[Quiz](https://docs.google.com/forms/d/1oz0-9ERCk7JzkXA2ZfoYttxdePDg249RMKOdEB42kqQ/viewform)


  7. Species, speciation, taxonomy [PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics7OMeara.pdf)


  8. Diversification [PDF](http://brianomeara.info/sites/default/files/2014_UTKEEB_Core_Phylogenetics8OMeara.pdf)


**Study Guide**
I had three main goals in this section: making sure you know what sort of questions you can address using phylogenies, having some idea of what methods are available (or close to being available, with a little work) to answer these questions, and having the basic understanding to read and know how to build a tree.
Things you won’t have to know: the difference between gamma and kappa, the equation for multivariate normal, authors behind methods, or similar specifics that you’ll forget again in a month. What I do want you to know:




  * How are trees made?


  * Why are trees made?


  * Compare and contrast a phylogram and a chronogram.


  * Given a tree, answer questions about its topology or other features (i.e., what’s the closest relative to X on the tree?).


  * Compare and contrast bootstrapping and Bayesian approaches for understanding uncertainty.


  * What is a continuous time Markov chain with a finite state space? 


  * Why do we care about the above?


  * How are models for DNA related to models for a binary morphological trait?


  * Connect the central limit theorem to the multivariate normal. Why does this make sense for an evolutionary model?


  * What is independent contrasts? When would you use this?


  * What are ways to deal with heterogeneity of processes on a tree? Why is this important?


  * What is tree stretching? What questions does this let you ask?


  * What are sister group comparisons used for?


  * What is the difference between Bayesian and likelihood approaches?


  * Compare and contrast hypothesis testing, model selection, and parameter estimation.


  * What are some approaches to understanding diversification?


  * Why are there methods for jointly looking at diversification and trait evolution?


  * Given a certain biological question, I may ask you what sort of approach you would take to it. The various empirical examples should help with this.


Note that this is the content I want you to know, but not necessarily the questions. There would not be time for these to be essay questions, so I will ask for some of this information in short answer questions and just a few essays.

