---
author: brianomeara_ra6153
comments: false
date: 2015-11-30 05:27:03+00:00
layout: post
link: http://www.brianomeara.info/2015/11/30/macroevolution-2015-study-guide/
slug: macroevolution-2015-study-guide
title: 'Macroevolution 2015: Study guide'
wordpress_id: 436
categories:
- Macroevolution
- Teaching
---

Study guide/possible exam questions for EEB464 Macroevolution. This focuses on the essay type questions for the exam.



	
  * Why may life have been single celled for a long time?

	
  * Describe a major event (such as a mass extinction, colonization of land, etc.) and its subsequent effects.

	
  * How do we learn about organisms with no living descendants, such as trilobites? How would living descendants affect how we can learn about them?

	
  * Can behavior be fossilized? If so, give two examples.

	
  * How can something become a fossil?

	
  * How has continental drift affected the location of organisms?

	
  * Why don’t barracuda eat cleaner wrasse?

	
  * Why bother making phylogenies?

	
  * What is a phylogeny?

	
  * Can species be treated as independent data points in a statistical analysis? Why or why not?

	
  * How can movement of land lead to speciation?

	
  * What was the Great Faunal Interchange?

	
  * Describe island biogeography. Why is it relevant to this class?

	
  * Contrast pre and postzygotic mating barriers

	
  * What are Dobzhansky-Muller Incompatibilities?

	
  * Compare allopatric and sympatric speciation.

	
  * How might hybrids have greater fitness than their parents?

	
  * Explain the importance of Wolbachia.

	
  * Describe the cause of a contemporary group of extinctions.

	
  * Give an example of a biological trait that may increase extinction risk. Why might it?

	
  * How could phylogenetic diversity be useful for conservation?

	
  * Describe a simple model for species diversification.

	
  * Compare and contrast speciation rate and diversification rate.

	
  * How may trait transitions and diversification rates together affect evolution of a group?

	
  * Compare likelihood and Bayesian approaches.

	
  * Which requirement for natural selection is most important? Why?

	
  * What, in the context of this class, is an advantage of sexual reproduction?

	
  * Describe Muller’s ratchet

	
  * Describe one mechanism of sexual selection.

	
  * What is Cope’s rule? Why might it be true?

	
  * Contrast what a passive and an active trend mean.

	
  * How would you detect evidence of a trend?

	
  * Contrast mutualism with parasitism. How can one change into the other?

	
  * Give an example of a commensalism.

	
  * Define what is an evolutionarily stable strategy?

	
  * Why is “the good of the species” a problematic concept?

	
  * Why might a prey item call out to a predator?

	
  * What is inclusive fitness?

	
  * What is Hamilton’s rule?

	
  * Give a behavior the idea of inclusive fitness could explain.

	
  * Why can it be empirically difficult to know if two populations are the same or different species?

	
  * Relate Darwin’s work on reefs to his work on evolution.

	
  * What are some potential reasons that gliding evolves much more often than flight?

	
  * What evidence links humans to some megafaunal extinctions?

	
  * Pasteur showed life does not spontaneously appear. Biologists believe life originally spontaneously appeared. Reconcile these views.

	
  * Use insects as an example of a macroevolutionary process.

	
  * What may explain evolution of intelligence?

	
  * What factors affect evolution of virulence in diseases?

	
  * How would you test the idea of punctuated equilibrium?

	
  * Have marsupials converged on placental mammals more than you’d expect under a null model? Why or why not?

	
  * How do we reconstruct language evolution?

	
  * How have animals and plants been domesticated?

	
  * Are humans still evolving? Why or why not?

	
  * Relate evolutionary models to disease.


