---
author: brianomeara_ra6153
comments: false
date: 2015-07-28 03:57:34+00:00
layout: post
link: http://www.brianomeara.info/2015/07/28/teaching-overview/
slug: teaching-overview
title: Teaching overview
wordpress_id: 82
categories:
- Teaching
---

I teach a variety of classes: usually a portion of the [Graduate Core](http://brianomeara.info/category/grad-core/) course (phylogenetics), a mandatory course for all graduate students; a 400-level (upper level undergrads and beginning grad students) course on [macroevolution](http://brianomeara.info/category/macroevolution); introductory biology ([Biodiversity](http://brianomeara.info/category/biodiversity/): Bio150); and a variety of smaller graduate seminars. My usual teaching load is [Macroevolution](http://brianomeara.info/category/macroevolution/) every fall, [Core](http://brianomeara.info/category/grad-core/) every fall, [Biodiversity](http://brianomeara.info/category/biodiversity/) every other spring, and usually a graduate seminar or two (often [phyloseminar](http://brianomeara.info/category/phyloseminar/)) per semester. In 2015-16, I’ll be stepping back from teaching Core to start a new, intensive graduate class on phylogenetic methods.
You can check the links above for updates to the courses, but an even easier way is to subscribe to an RSS feed. This is a way websites can let readers know when a new post is available; a popular free app for receiving these updates (on the web, iOS, or Android) is feedly, but there are many others, and some web browsers (Explorer, the newest Safari, Firefox, but not Chrome) also support this.

I am always eager to get feedback on teaching: please do that at
[http://www.brianomeara.info/teaching/feedback](http://www.brianomeara.info/teaching/feedback)
