---
author: brianomeara_ra6153
comments: false
date: 2015-10-02 05:29:46+00:00
layout: post
link: http://www.brianomeara.info/2015/10/02/macroevolution-midterm/
slug: macroevolution-midterm
title: 'Macroevolution: Midterm'
wordpress_id: 328
categories:
- Macroevolution
- Teaching
---


	
  1. Sea levels are rising due to global warming. Imagine a rugged landmass that will then be subdivided due to ocean barriers. How will this affect speciation, extinction, and diversification rates? Why?

	
  2. How could a taphonomic bias affect our interpretation of Cope’s rule?

	
  3. The appendix periodically gets inflamed and can even lead to death. Give a hypothesis for why humans have it and how you could test this hypothesis.

	
  4. How could you test the idea that mosquitos evolved the ability to bite mammals due to natural selection?

	
  5. What maintains an even sex ratio in many species?

	
  6. Many species go through costly male competition: which male has the brightest tail, prettiest bower, loudest call. You watch a nature documentary that says this is for the good of the species, so that only the best males pass on their genes and so the species as a whole improves. Is this accurate? Why or why not?

	
  7. Describe Dobzhansky-Muller incompatibilities and their importance.

	
  8. Describe a major event in earth history and how life would be different today had it not happened.


