---
author: brianomeara_ra6153
comments: false
date: 2015-08-18 15:54:42+00:00
layout: post
link: http://www.brianomeara.info/2015/08/18/macroevolution-2015-syllabus/
slug: macroevolution-2015-syllabus
title: Macroevolution 2015 syllabus
wordpress_id: 201
categories:
- Macroevolution
- Teaching
---

Here's the syllabus for EEB464 Macroevolution this year. I have it here in HTML as well as [.docx](http://brianomeara.info/wordpress_beta/wp-content/uploads/2015/08/UTK_2015_Fall_EEB464_SyllabusV01.docx) and [.pdf](http://brianomeara.info/wordpress_beta/wp-content/uploads/2015/08/UTK_2015_Fall_EEB464_SyllabusV01.pdf). Course announcements will come through the official BlackBoard site but materials will appear here, where they are available to all.


* * *



EEB 464 Macroevolution Fall 2015
Instructor: Dr. Brian C. O’Meara
Office hrs: 1:30-2:30 M and by appointment; 446 Hesler
Meeting time: 10:10-11:00 MWF, 488 Dabney
Description:
The course is a lecture format course with classroom discussion and participation. Students are introduced to fundamental concepts in macroevolution including current areas of debate (drivers of evolutionary rates, modes of speciation, etc.) and taught to think critically. Computer-based exercises, especially simulations, will allow students to learn how processes acting on short to medium time scales affect long term patterns. 3 credits

To understand macroevolution, it is important to learn about who, what, where, when, how, and why.

Who: Organisms
What: Non-living context (rocks from space, environmental conditions)
Where: Biogeography (on Pangaea or Bermuda?)
When: Geological time scale
How: Pattern of evolution
Why: Process of evolution

The course will cover all these areas. The ones that are most interesting, of course, are the how and especially the why. These are also the best to cover in class, where there can be discussion and other interaction. Rote learning (word meanings and the like) is something that you should be able to do on your own at this point in your education, with occasional guidance. We’re not going to use much class time on this, but you will have to learn this info. I will clearly describe what you do have to learn (and if it’s not clear, ASK), and quizzes and tests will be ways to evaluate your progress and provide further incentive to learn.

**Biology program learning objectives:**
I include how this course addresses these in _italics._
Explain and provide examples of each the five big ideas in Biology, using their knowledge of biological concepts gained from their course of study:



	
  * Evolution: Populations of organisms and their cellular components have changed over time through both selective and non-selective evolutionary processes. _This is the main point of the course, and will be covered in every lecture and activity._

	
  * Structure and Function: All living systems (organisms, ecosystems, etc.) are made of structural components whose arrangement determines the function of the systems. _This will be highlighted especially in the discussions of morphological evolution (flight, insects, etc.)_

	
  * Information Flow and Storage: Information (DNA, for example) and signals are used and exchanged within and among organisms to direct their functioning. _Origin of life will cover this extensively._

	
  * Transformations of Energy and Matter: All living things acquire, use, and release and cycle matter and energy for cellular / organismal functioning. _The discussion of escalation focuses on this, and it comes up in background on the focal organisms._

	
  * Systems: Living systems are interconnected, and they interact and influence each other on multiple levels. _Speciation, extinction, discussion, and history of life all cover this._


Demonstrate the ability to perform the following scientific practices:

	
  * Formulate empirically-testable hypotheses. _This is the point of the final presentation._

	
  * Interpret visual representations (figures and diagrams). _These will come up throughout the class, especially in the context of phylogenetic trees._

	
  * Evaluate data and come to a conclusion (with evidence) (formulate an argument). _Much of class discussion emphasizes this skill: I’ll present information and have you elaborate on this and provide potential explanations._



**Course learning objectives:**
By the end of this course, students will be able to:



	
  * Formulate, defend, and critically evaluate hypotheses about evolutionary mechanisms

	
  * Understand the context and reason for evolutionary patterns

	
  * Interpret information from fossils, phylogenies, and other data sources

	
  * Generate ideas for feasible, compelling scientific projects



To really understand evolution and converse with other scientists, you have to know the names of some groups (imagine trying to talk about the history of some musical genre without knowing the names of any musicians or songs in that genre). Thus, most days, you will be responsible for learning about a particular taxon (on the syllabus, below). This could be a single species or a clade of many species. You should learn very basic info: what is it, what is it related to (i.e., where it attaches to the tree of life we will grow over the class), why it is important to know. For example: “Angiosperms: all flowering plants, lots of species, became common in the Cretaceous but may have originated earlier, sister to Gnetales.” Working together on the website forum to get this info is encouraged (you can decide to rotate the job, let whoever gets the info first post it, etc.). What I really care about is that you learn it. Note that some of the taxa may be subsets of the other taxa (elephants are a kind of vertebrate).
Writing and presentations will be graded on a variety of levels, such as grammar, structure, and substance. The purpose of grading and comments is to improve your writing. Remember that your writing is being graded, not you.
Word count sets a minimum length (and references are not counted) but you may go a bit longer if needed (try to keep below 125% of required length). Since length is judged by words, not page length, please don’t do any odd formatting of your paper (huge or tiny margins, font sizes of 8 or 18, etc.) to try to meet some page limits.
Papers/midterms will be turned in via Online@UT. This eliminates issues with printers, odd file formats, and the like. The site will automatically check your work for possible plagiarism. I do this in all my classes with written work. Except where noted, assignments are to be done individually. You must cite and reference work properly. **When in doubt about citation, plagiarism, or collaboration, ASK. **Please turn in work as plain text or RDF. This makes it easier for me to put them in one document so I can give you back grades with comments.
For help with submitting documents online, see [http://online.utk.edu/students/assignment.shtml](http://online.utk.edu/students/assignment.shtml). There is a practice uploading assignment that will allow you to test to make sure you can upload files correctly before the pressure of a deadline. If there is a problem at the moment of a deadline, email me your work instead to verify it is done on time (but normally you should be using BlackBoard).

We will be using laptops for some work in class. If you see the laptop cart in the classroom, take a laptop. When class is done, please return them to the cart and plug them in. Take care of them when you are using them. Some of our work will use the statistical analysis package R ([http://www.r-project.org/](http://www.r-project.org/)). It is free and work on Mac, Linux, and Windows. For some class activities (announced beforehand) it will be convenient to bring a laptop. If you do not have one, groups can pair up. If you wish to prepare your laptop beforehand, install R on your computer. Then, within R:

install.packages(“ctv”)
library(ctv)
install.views(“Phylogenetics”)

(you can do this with the graphical user interface as well).

Communication is very important. I have set up a forum on the BlackBoard site (Online@UT) for our course. If you post a question there, I will immediately be emailed about it and will respond on the forum (though perhaps not immediately). Emailing me directly will not be any faster (though do email me if the issue is better addressed one-on-one). The benefit of using the forum is that everyone can see the answers and there’s a chance that one of the other students will answer the question first. Feel free to use the forum for other class-related discussions.

Though we have the main BlackBoard site, and notices will come through there, I will also be posting things (like slides) to [http://brianomeara.info/category/macroevolution/](http://brianomeara.info/category/macroevolution/) . Why a second site? The BlackBoard site is only active during the course and only to students enrolled in the course. You might want to look at the materials in other semesters, show your friends/family what you were learning, etc., so I have the public site that will persist.

Attendance is expected at all classes, though missing a class or two due to illness, family problem, etc. might happen (and is strongly suggested in the case of flu: [http://studenthealth.utk.edu/common_avoidflu.php](http://studenthealth.utk.edu/common_avoidflu.php) )

We will have discussions in nearly all classes. You should participate in them. Sometimes, discussions in a class such as this consist of students trying to return the right answer to the instructor’s question. To avoid this, sometimes I pursue a policy of not talking during a discussion for several minutes or longer so you have to talk to each other. This can result in complete silence. If you find this annoying, talk! Even if there is not a formal discussion, please ask questions at any point during class.

We will be using Turning Point clickers in this class. Many of you will already have them from UT. They cost about $50 at the bookstore and can be used throughout your remaining career here. Note that you while you cannot use someone else’s from this class, you should be able to borrow a friend’s who is not in this class (as long as you use that same one consistently). See the Blackboard site for more on how to use clickers. Our class is now large enough that keeping track of participation manually is infeasible. **I would like everyone to have a clicker by Aug 31.**

Late work is penalized at 10%/day (so something turned in 49 hours late is given a score 70% of what it would have received on the due date). Extensions are not normally granted, except under extraordinary circumstances (having too much work to do does not qualify, for example). Remember that even if you turn something in seven days late, it is still worth more points than not turning it in at all (and the grading for the class is just #points received / #points available, so something getting 20/100 points is still worth twice something getting 10/100 points, even though they are both an “F” individually).

My goal is to have you learn. If you are having trouble with something in the course, or if there is a topic you just have to learn more about, let me know (email, office hours, online forum, etc.). Faculty often use evaluations at the end of the semester to get info from students so we can improve before the next class, but this does not help you directly. **To allow the class to improve while you are taking it, I have created a site for anonymous feedback at http://brianomeara.info/teaching/feedback/ **(and yes, it is really anonymous). Let me know things that are going well or poorly — both are important. I might not implement all your suggestions, but they will all be read and considered, generally the same day you submit them.

Any student who feels s/he may need an accommodation based on the impact of a disability should contact me privately to discuss specific needs. Please contact the Office of Disability Services at 865-974-6087 in Dunford Hall to coordinate reasonable accommodations for students with documented disabilities.

All relevant University policies (including, but not limited to, policies on academic integrity, attendance, etc.) apply to this course. In the case of any conflict between the policies in this syllabus and University policy, University policy applies. The instructor reserves the right to revise, alter, and/or amend this syllabus as necessary. Students will be notified by email of any such revisions, alterations, and/or amendments.



<table width="663" style="height: 2396px;" >
<tbody >
<tr >

<td width="19" >#
</td>

<td width="51" >Date
</td>

<td width="152" >Topic
</td>

<td width="106" >Taxon to have learned
</td>

<td width="92" >Assignment
</td>
</tr>
<tr >

<td >
</td>

<td >19-Aug
</td>

<td >Pre-test, syllabus
</td>

<td >-
</td>

<td >
</td>
</tr>
<tr >

<td >1
</td>

<td >21-Aug
</td>

<td >History of planet & life
</td>

<td >Crinoid
</td>

<td >
</td>
</tr>
<tr >

<td >2
</td>

<td >24-Aug
</td>

<td >History of planet & life
</td>

<td >Archaea
</td>

<td >
</td>
</tr>
<tr >

<td >3
</td>

<td >26-Aug
</td>

<td >Evidence
</td>

<td >Bdelloid rotifers
</td>

<td >
</td>
</tr>
<tr >

<td >4
</td>

<td >28-Aug
</td>

<td >Taphonomy
</td>

<td >Trilobite
</td>

<td >
</td>
</tr>
<tr >

<td >5
</td>

<td >31-Aug
</td>

<td >Jargon
</td>

<td >Acromyrmex
</td>

<td >
</td>
</tr>
<tr >

<td >6
</td>

<td >2-Sep
</td>

<td >Phylogenetics
</td>

<td >Ammonite
</td>

<td >
</td>
</tr>
<tr >

<td >7
</td>

<td >4-Sep
</td>

<td >Empirical distributions
</td>

<td >Ichthyornis dispar
</td>

<td >
</td>
</tr>
<tr >

<td >
</td>

<td >7-Sep
</td>

<td >Labor Day
</td>

<td >
</td>

<td >
</td>
</tr>
<tr >

<td >8
</td>

<td >9-Sep
</td>

<td >Biogeography
</td>

<td >HIV
</td>

<td >
</td>
</tr>
<tr >

<td >9
</td>

<td >11-Sep
</td>

<td >Speciation
</td>

<td >Wolbachia
</td>

<td >
</td>
</tr>
<tr >

<td >10
</td>

<td >14-Sep
</td>

<td >Speciation
</td>

<td >Anomalocaris
</td>

<td >
</td>
</tr>
<tr >

<td >11
</td>

<td >16-Sep
</td>

<td >Extinction
</td>

<td >Gasterosteus aculeatus
</td>

<td >
</td>
</tr>
<tr >

<td >12
</td>

<td >18-Sep
</td>

<td >Extinction
</td>

<td >Geospizinae
</td>

<td >Paper due at 8 pm
</td>
</tr>
<tr >

<td >13
</td>

<td >21-Sep
</td>

<td >Diversification
</td>

<td >Dionaea muscipula
</td>

<td >
</td>
</tr>
<tr >

<td >14
</td>

<td >23-Sep
</td>

<td >Diversification
</td>

<td >Tribolium
</td>

<td >
</td>
</tr>
<tr >

<td >15
</td>

<td >25-Sep
</td>

<td >Natural selection & drift
</td>

<td >bonobo
</td>

<td >
</td>
</tr>
<tr >

<td >16
</td>

<td >28-Sep
</td>

<td >Sex
</td>

<td >Lichen
</td>

<td >
</td>
</tr>
<tr >

<td >17
</td>

<td >30-Sep
</td>

<td >Trends
</td>

<td >Fig wasp
</td>

<td >
</td>
</tr>
<tr >

<td >18
</td>

<td >2-Oct
</td>

<td >Symbiosis
</td>

<td >Anolis
</td>

<td >Midterm distributed
</td>
</tr>
<tr >

<td >19
</td>

<td >5-Oct
</td>

<td >Game theory
</td>

<td >Tunicates
</td>

<td >
</td>
</tr>
<tr >

<td >20
</td>

<td >7-Oct
</td>

<td >Inclusive fitness
</td>

<td >Brachiopod
</td>

<td >
</td>
</tr>
<tr >

<td >21
</td>

<td >9-Oct
</td>

<td >Systematics
</td>

<td >Spiny anteater
</td>

<td >
</td>
</tr>
<tr >

<td >22
</td>

<td >12-Oct
</td>

<td >Darwin
</td>

<td >Eubacteria
</td>

<td >Midterm due at 8 pm
</td>
</tr>
<tr >

<td >23
</td>

<td >14-Oct
</td>

<td >Escalation
</td>

<td >Maiasaura
</td>

<td >
</td>
</tr>
<tr >

<td >
</td>

<td >16-Oct
</td>

<td >Fall break
</td>

<td >
</td>

<td >
</td>
</tr>
<tr >

<td >24
</td>

<td >19-Oct
</td>

<td >Flight
</td>

<td >Isopod
</td>

<td >
</td>
</tr>
<tr >

<td >25
</td>

<td >21-Oct
</td>

<td >Dominance
</td>

<td >Riftia pachyptila
</td>

<td >
</td>
</tr>
<tr >

<td >26
</td>

<td >23-Oct
</td>

<td >Invasive humans
</td>

<td >Ground sloth
</td>

<td >
</td>
</tr>
<tr >

<td >27
</td>

<td >26-Oct
</td>

<td >Disease evolution
</td>

<td >Thermus aquaticus
</td>

<td >
</td>
</tr>
<tr >

<td >28
</td>

<td >28-Oct
</td>

<td >Origin of life
</td>

<td >Lycophytes
</td>

<td >
</td>
</tr>
<tr >

<td >29
</td>

<td >30-Oct
</td>

<td >Contemporary evolution
</td>

<td >Strepsiptera
</td>

<td >
</td>
</tr>
<tr >

<td >30
</td>

<td >2-Nov
</td>

<td >Insects
</td>

<td >Diatom
</td>

<td >
</td>
</tr>
<tr >

<td >31
</td>

<td >4-Nov
</td>

<td >Stephen Jay Gould
</td>

<td >Dimetrodon
</td>

<td >
</td>
</tr>
<tr >

<td >32
</td>

<td >6-Nov
</td>

<td >Language evolution
</td>

<td >Buchnera
</td>

<td >
</td>
</tr>
<tr >

<td >33
</td>

<td >9-Nov
</td>

<td >Discoveries from past month
</td>

<td >Welwitschia
</td>

<td >
</td>
</tr>
<tr >

<td >34
</td>

<td >11-Nov
</td>

<td >Evolution of intelligence
</td>

<td >Ginkgo
</td>

<td >
</td>
</tr>
<tr >

<td >35
</td>

<td >13-Nov
</td>

<td >Free topic 1
</td>

<td >silversword
</td>

<td >
</td>
</tr>
<tr >

<td >36
</td>

<td >16-Nov
</td>

<td >Free topic 2
</td>

<td >orca
</td>

<td >
</td>
</tr>
<tr >

<td >37
</td>

<td >18-Nov
</td>

<td >Free topic 3
</td>

<td >Cordyceps
</td>

<td >
</td>
</tr>
<tr >

<td >38
</td>

<td >20-Nov
</td>

<td >Presentations
</td>

<td >
</td>

<td >Presentation
</td>
</tr>
<tr >

<td >39
</td>

<td >23-Nov
</td>

<td >Presentations
</td>

<td >
</td>

<td >Presentation
</td>
</tr>
<tr >

<td >40
</td>

<td >25-Nov
</td>

<td >Presentations
</td>

<td >
</td>

<td >Presentation
</td>
</tr>
<tr >

<td >
</td>

<td >27-Nov
</td>

<td >Thanksgiving break
</td>

<td >
</td>

<td >
</td>
</tr>
<tr >

<td >41
</td>

<td >30-Nov
</td>

<td >Review
</td>

<td >
</td>

<td >
</td>
</tr>
<tr >

<td >
</td>

<td >4-Dec
</td>

<td >Final exam 8 - 10 am
</td>

<td >Sorry.
</td>

<td >
</td>
</tr>
</tbody>
</table>
**[UTK_2015_Fall_EEB464_SyllabusV01.pdf](http://brianomeara.info/wordpress_beta/wp-content/uploads/2015/08/UTK_2015_Fall_EEB464_SyllabusV01.pdf)Grading:**
100 points: Topic review. 1000 words, including references. Cover a macroevolutionary question: what is known about it, what is the state of work on it, what work might be done in the future? Work should be individual.
100 points: Pair presentation. Imagine you are trying to get money to study a macroevolutionary question. You have to make a compelling case to a potential funder (i.e., the NSF will give you $15K to study it, or a professor might offer you a place in her lab to work on this). You should include 1) why that question is interesting (this should include what is known about it), 2) how you plan to address it, 3) what potential outcomes of your work may be, and 4) the implications of these. 10 minute talk (PowerPoint, Keynote, PDF, etc.). Be sure to include references in your slides.
150 points: Class work. This includes clicker questions (many of which have points regardless of the answer), quizzes, and other in class assignments. In general, these will not be announced in advance. Note that 180 points will actually be assigned but the maximum score possible will be 150 points. The goal of this is to allow you to miss some classes (due to illness, death in the family, or other such reasons) without needing to bring a note justifying your absence.
100 points: Take home midterm. You may NOT work with classmates or other humans, but you can use notes, books, papers, etc. (though do not plagiarize them, not that the questions will be ones you can typically plagiarize).
200 points: Final exam. Similar to the midterm, but with a bit more evaluation of rote knowledge.
In addition to these assignments, students will periodically be given articles to read for later discussion. Clicker questions or quizzes will assess whether the articles have been read.
