originalwd <- getwd()
setwd("/Users/bomeara/Documents/MyDocuments/GitClones/brianomearainfo/docs")
rmarkdown::render_site()
source("functions.R")
sitemap <- GenerateSitemap()
cat(sitemap, file="sitemap.xml")
system("git add .; git commit -m'updating site'; git push")
setwd(originalwd)
quit(save="no")
