originalwd <- getwd()
Sys.setenv(RSTUDIO_PANDOC="/Applications/RStudio.app/Contents/MacOS/pandoc")
setwd("/Users/bomeara/Documents/MyDocuments/GitClones/brianomearainfo/docs")
try(system('mv ~/Downloads/7\\ LIVE_saliva_test_data_Page\\ 1_Table.csv .'))
try(system('mv ~/Downloads/8\\ LIVE_SHC_test_data_Page\\ 1_Table.csv .'))
try(system('mv ~/Downloads/2\\ new\\ cases_Page\\ 1_Time\\ series.csv .'))
try(system('mv ~/Downloads/LIVE\\ saliva\\ positivity\\ rate_Page\\ 1_Bar\\ chart.csv .'))
try(system('mv ~/Downloads/LIVE\\ spring\\ 2021\\ saliva\\ table_Page\\ 1_Table.csv .'))

rmarkdown::render_site()
source("functions.R")
print("Not creating sitemap")
#sitemap <- GenerateSitemap()
#cat(sitemap, file="sitemap.xml")
system("git add .; git commit -m'updating site'; git push")
setwd(originalwd)
print(Sys.time())
print("/Users/bomeara/Documents/MyDocuments/GitClones/brianomearainfo/docs/covid.html")
quit(save="no")
