---
layout: opportunities
link: https://www.brianomeara.info/opportunities/
slug: opportunities
title: Opportunities
---

There are several kinds of opportunities for joining the lab. 

Standard lab policy is that you should reach out to [current and past lab members](https://brianomeara.info/personnel.html) for feedback on what it's like here, and **never** tell me what they say, positive or negative. That way they know they can be frank with you.

I also suggest you tell me about other things you may need -- spousal accommodations, info about child care, etc. -- only once you receive an official offer. I can try to work with you on ways to help, but this way, neither I nor anyone else involved can discriminate against you based on these factors, even unconsciously, before you get an offer.

You might look at [lab guidelines](https://brianomeara.info/guidelines.html) to get a sense of how the lab works. Materials I created for [promotion](https://brianomeara.info/promotion.html), especially the promotion packet itself ([PDF](https://brianomeara.info/files/OMearaPromotionPacket.pdf)) may give you a good summary of where my teaching, research, and service have been and are going. For what you might learn here, [learning objectives](https://brianomeara.info/learningobjectives.html) can be helpful.

## Postdocs

### Sept. 2019

There are three postdoc positions. They can be remote or local to Knoxville. In general, the lab is run in such a way that working remotely is fine -- lab meetings are virtual for everyone, we have a group chat in slack, we do work through GitHub, etc. It can be good to be here (seminars, social connections with others) but not everyone has the flexibility to move.

Two are for continuing development of Approximate Bayesian Computation approaches for phylogenetics. We have a method for single continuous traits almost ready (doing final simulations on it now) but we want to extend it to discrete traits, multivariate traits, and more. To apply for this, go to [here](https://ut.taleo.net/careersection/ut_system/jobdetail.ftl?job=19000001LL&tz=GMT-04%3A00&tzname=America%2FNew_York).

The other is for a postdoc working on ascertainment bias in diversification models. This is for a grant in collaboration with [Jeremy Beaulieu](https://www.jeremybeaulieu.org/). To apply for this, go to [here](https://ut.taleo.net/careersection/ut_system/jobdetail.ftl?job=19000001LM&tz=GMT-04%3A00&tzname=America%2FNew_York).

Please reach out to me for details (apply via the links above, but do contact me directly, too). Positions are open until filled, but I want to fill them soon.

## Grad students

I am not currently looking for grad students to join my lab. But for people curious about opportunities in the future: 

* Students are admitted to the program, not to the lab. That means that it's not just up to me, and if you don't end up liking the first lab you join, moving is possible. You still have to have a faculty member saying, "I want them in my lab" to get in.
* Reach out to me ([email](mailto:bomeara@utk.edu) or [twitter](https://twitter.com/omearabrian) work well). We can talk about your interests, expectations, etc. There's also the possibility of fee waivers for applying (not really a waiver -- just that the lab will pay your fee to the graduate school). Like an [increasing number of other programs](https://www.sciencemag.org/careers/2019/05/wave-graduate-programs-drop-gre-application-requirement) that care about pulling students from a talented, diverse pool, rather than the pool who can pay to prove they know about odd numbers, parallel lines, and bar graphs ([really!](https://www.ets.org/gre/revised_general/prepare/quantitative_reasoning/)), we no longer require the GRE. However, some programs still do -- you should be applying to several programs, so see if any on your list still use the GRE before you decide not to take it at all.
* I can teach you about active questions in evolution, methods use and development, programming, and more. I cannot make you curious and driven. Given how our graduate program and especially how my lab runs, you shouldn't expect to be handed a research topic from above -- you will develop your research topic(s) with my help and the help of your committee. I will thus ask you to propose some concrete research ideas as a filter -- it's not a commitment that you're going to work on them, but a way to see if you care about particular ideas.
* We try to treat graduate students humanely: for those making adequate progress, tuition is covered (but not [fees](https://onestop.utk.edu/tuition-detail/)), you're in a health care plan, you get a $20K/year stipend. In exchange, you're expected to TA every semester (but not summer) -- the TA time load is ~20 hours per week. 90% of our students report that this is functionally a living wage for the area (but some students feel this is too low). Students also can apply for research funds (most students receive them, but in varying amounts) and of course there are other grants as well. There is also an active graduate student group, [GREBE](https://grebeemail.wixsite.com/grebe), which has representatives at faculty meetings and most committees (they're excluded them from the grad admissions committee over privacy concerns).
* Grad school is a path to many careers: governmental agencies, private companies, NGOs, academia, and more. I will try to support you in whatever career you feel is best for you (and this can change during your time in grad school), and your intended career plays no role in whether I want you in the lab or not. Do note that, like most academics, my training and professional contacts are generally in academia, but that does not mean I won't be able to help with other careers.
* Grad school, especially for people with the intention of ending up in a tenure track job, has benefits and costs that not all people applying may know about. I have a [page](https://brianomeara.info/shouldyougotogradschool.html) on this -- please read it before choosing this path.
* Matt Might has a good [visual guide](https://matt.might.net/articles/phd-school-in-pictures/) of what it means to get a PhD (though Masters is similar; in our field, it's ~1/3 of the research effort, but still represents a contribution to knowledge).
* Risk factors: If you move somewhere to work with someone, it's nice to know they'll remain there. Folks do move around in science, but I have no imminent plans to do so. I try to run my lab very transparently, so if I do start considering a move, I will let lab members know (unless they don't want to be told until it's a sure thing to reduce stress). Another kind of risky move (from a student perspective) is the advisor moving into administration and thus having little time for mentorship and research. I do have an administrative role now (one of two associate heads) but its workload is manageable (and I've handled additional admin roles at the same time, such as associate director of NIMBioS, in the past). I am in science to solve evolutionary questions, not to be a manager of people, so I'm not actively looking for roles here. It's not impossible I'll be pulled in to some sort of role eventually, but as with other moves, I will discuss this with lab members.

For application information, go to https://eeb.utk.edu/graduate-studies/application-information/ (though note we are changing our deadline to Dec. 1). There is information at a university level for applying at https://gradschool.utk.edu/admissions/applying-to-graduate-school/. Students from countries outside the US are more than welcome. See https://gradschool.utk.edu/admissions/applying-to-graduate-school/admissions-for-international-students/ for more information (remember our department deadline of Dec. 1, which is earlier than the university deadline). Our [international office](https://international.utk.edu/) can help with visas and other information (and students who have worked with this office generally find it helpful). Also note that United States national policy affects visas and related paperwork, and so what is required and permissible may change.

## Undergrads

There are no entry level jobs in the lab: there are no turtles to feed, beakers to clean, seeds to count. Instead, I typically work with students to develop research questions they care about (past ones have included Slavic language evolution and evolution of salamander development). It is like a graduate student dissertation, just shorter and perhaps more accessible. So if you have some question you're curious about, even if it's vague ("I really like speciation", "Phylogenetic trees are awesome"), email me to set up a time we can talk. We can typically arrange for you to receive research credit for the research you are doing. The earlier you do this, the better -- it gives you time to learn more skills to better answer your questions and really consider the biology.
