

## Publications: Papers


According to Google Scholar, my work has been cited 3937 times, and my h-index is 24. (Google Scholar tends to overestimate citations, however). Also note that I work under a very stringent criterion for when I get authorship -- I have to actively make a significant contribution to the research and writing to merit authorship. For example, in 2015-6, three lab members had papers in *Science* ([grad student Sam Borstein](http://science.sciencemag.org/content/350/6264/1077.long), [postdoc Nick Matzke](http://science.sciencemag.org/content/351/6268/28), and [postdoc Sandy Kawano](http://science.sciencemag.org/content/353/6295/154.full)) but I am, appropriately to my mind, not an author on any of these.



Beaulieu, J. M. and B. C. **O'Meara** (2018a). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018b). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018c). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018d). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018e). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018f). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018g). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018h). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Beaulieu, J. M. and B. C. **O'Meara** (2018i). "Can we build it? Yes
we can, but should we use it? Assessing~the quality and value of a
very large phylogeny of~campanulid angiosperms". In: _American
Journal of Botany_ 105.3, pp. 417-432.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017a). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017b). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017c). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017d). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017e). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017f). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017g). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017h). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Jackson, N. D, A. E. Morales, B. C. Carstens, and B. C. **O'Meara**
(2017i). "PHRAPL: Phylogeographic Inference Using Approximate
Likelihoods". In: _Systematic Biology_ 66.6, pp. 1045-1053.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017a). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017b). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017c). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017d). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017e). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017f). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017g). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017h). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Carstens, B. C, A. E. Morales, N. D. Jackson, and B. C. **O'Meara**
(2017i). "Objective choice of phylogeographic models". In:
_Molecular Phylogenetics and Evolution_ 116, pp. 136-140.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017a). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017b). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017c). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017d). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017e). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017f). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017g). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017h). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Bosco, J. M, S. E. Riechert, and B. C. **O'Meara** (2017i). "The
ontogeny of personality traits in the desert funnel-web spider,
Agelenopsis lisa (Araneae: Agelenidae)". In: _Ethology_ 123.9. Ed.
by E. Hebets, pp. 648-658.

Schwery, O. and B. C. **O'Meara** (2016a). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016b). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016c). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016d). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016e). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016f). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016g). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016h). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

Schwery, O. and B. C. **O'Meara** (2016i). "MonoPhy: a simple R
package to find and visualize monophyly issues". In: _PeerJ
Computer Science_ 2, p. e56.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016a).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016b).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016c).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016d).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016e).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016f).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016g).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016h).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C, S. D. Smith, W. S. Armbruster, L. D. Harder, C. R.
Hardy, L. C. Hileman, L. Hufford, A. Litt, S. Magallón, S. A.
Smith, P. F. Stevens, C. B. Fenster, and P. K. Diggle (2016i).
"Non-equilibrium dynamics and floral trait interactions shape
extant angiosperm diversity". In: _Proceedings of the Royal
Society B: Biological Sciences_ 283.1830, p. 20152304.

**O'Meara**, B. C. and J. M. Beaulieu (2016a). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016b). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016c). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016d). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016e). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016f). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016g). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016h). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

**O'Meara**, B. C. and J. M. Beaulieu (2016i). "Past, future, and
present of state-dependent models of diversification". In:
_American Journal of Botany_ 103.5, pp. 792-795.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016a). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016b). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016c). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016d). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016e). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016f). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016g). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016h). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Morales, A. E, N. D. Jackson, T. A. Dewey, B. C. **O'Meara**, and B.
C. Carstens (2016i). "Speciation with Gene Flow in North
AmericanMyotisBats". In: _Systematic Biology_, p. syw100.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016a). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016b). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016c). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016d). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016e). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016f). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016g). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016h). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Jackson, N. D, B. C. Carstens, A. E. Morales, and B. C. **O'Meara**
(2016i). "Species Delimitation with Gene Flow". In: _Systematic
Biology_, p. syw117.

Beaulieu, J. M. and B. C. **O'Meara** (2016a). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016b). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016c). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016d). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016e). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016f). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016g). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016h). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Beaulieu, J. M. and B. C. **O'Meara** (2016i). "Detecting Hidden
Diversification Shifts in Models of Trait-Dependent Speciation and
Extinction". In: _Systematic Biology_ 65.4, pp. 583-601.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015a). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015b). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015c). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015d). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015e). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015f). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015g). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015h). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015i). "Zanne et al.
reply". In: _Nature_ 521.7552, pp. E6-E7.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015j). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015k). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015l). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015m). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015n). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015o). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015p). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015q). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2015r). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 521.7552, pp. 380-380.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015a). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015b). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015c). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015d). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015e). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015f). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015g). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015h). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015i). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015j). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015k). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015l). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015m). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015n). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015o). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015p). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015q). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

**O'Meara**, B. C, K. L. Graham, S. M. Pellis, and G. M. Burghardt
(2015r). "Evolutionary models for the retention of
adult\textendashadult social play in primates: The roles of diet
and other factors associated with resource acquisition". In:
_Adaptive Behavior_ 23.6, pp. 381-391.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015a). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015b). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015c). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015d). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015e). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015f). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015g). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015h). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M, B. C. **O'Meara**, P. Crane, and M. J. Donoghue
(2015i). "Heterogeneous Rates of Molecular Evolution and
Diversification Could Explain the Triassic Age Estimate for
Angiosperms". In: _Systematic Biology_ 64.5, pp. 869-878.

Beaulieu, J. M. and B. C. **O'Meara** (2015a). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015b). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015c). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015d). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015e). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015f). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015g). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015h). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Beaulieu, J. M. and B. C. **O'Meara** (2015i). "Extinction can be
estimated from moderately sized molecular phylogenies". In:
_Evolution_ 69.4, pp. 1036-1043.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015a). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015b). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015c). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015d). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015e). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015f). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015g). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015h). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Aldrovandi, M. S. P, J. E. Johnson, B. OMeara, R. H. Petersen, and
K. W. Hughes (2015i). "The Xeromphalina campanella/kauffmanii
complex: species delineation and biogeographical patterns of
speciation". In: _Mycologia_ 107.6, pp. 1270-1284.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014a). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014b). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014c). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014d). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014e). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014f). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014g). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014h). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2014i). "Corrigendum:
Three keys to the radiation of angiosperms into freezing
environments". In: _Nature_ 514.7522, pp. 394-394.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014a). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014b). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014c). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014d). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014e). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014f). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014g). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014h). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Williams, J. H, M. L. Taylor, and B. C. **O'Meara** (2014i). "Repeated
evolution of tricellular (and bicellular) pollen". In: _American
Journal of Botany_ 101.4, pp. 559-571.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014a).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014b).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014c).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014d).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014e).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014f).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014g).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014h).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Jhwueng, D, S. Huzurbazar, B. C. **O'Meara**, and L. Liu (2014i).
"Investigating the performance of AIC in selecting phylogenetic
models". In: _Statistical Applications in Genetics and Molecular
Biology_ 13.4.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014a). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014b). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014c). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014d). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014e). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014f). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014g). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014h). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Cornwell, W. K, M. Westoby, D. S. Falster, R. G. FitzJohn, B. C.
**O'Meara**, M. W. Pennell, D. J. McGlinn, J. M. Eastman, A. T. Moles,
P. B. Reich, D. C. Tank, I. J. Wright, L. Aarssen, J. M. Beaulieu,
R. M. Kooyman, M. R. Leishman, E. T. Miller, Ü. Niinemets, J.
Oleksyn, A. Ordonez, D. L. Royer, S. A. Smith, P. F. Stevens, L.
Warman, P. Wilf, and A. E. Zanne (2014i). "Functional
distinctiveness of major plant lineages". In: _Journal of Ecology_
102.2. Ed. by A. Austin, pp. 345-356.

Banbury, B. L. and B. C. **O'Meara** (2014a). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014b). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014c). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014d). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014e). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014f). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014g). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014h). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Banbury, B. L. and B. C. **O'Meara** (2014i). "Reol: R interface to
the Encyclopedia of Life". In: _Ecology and Evolution_ 4.12, pp.
2577-2583.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013a). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013b). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013c). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013d). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013e). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013f). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013g). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013h). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Zanne, A. E, D. C. Tank, W. K. Cornwell, J. M. Eastman, S. A.
Smith, R. G. FitzJohn, D. J. McGlinn, B. C. **O'Meara**, A. T. Moles,
P. B. Reich, D. L. Royer, D. E. Soltis, P. F. Stevens, M. Westoby,
I. J. Wright, L. Aarssen, R. I. Bertin, A. Calaminus, R. Govaerts,
F. Hemmings, M. R. Leishman, J. Oleksyn, P. S. Soltis, N. G.
Swenson, L. Warman, and J. M. Beaulieu (2013i). "Three keys to the
radiation of angiosperms into freezing environments". In: _Nature_
506.7486, pp. 89-92.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013a). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013b). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013c). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013d). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013e). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013f). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013g). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013h). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Stoltzfus, A, H. Lapp, N. Matasci, H. Deus, B. Sidlauskas, C. M.
Zmasek, G. Vaidya, E. Pontelli, K. Cranston, R. Vos, C. O. Webb,
L. J. Harmon, M. Pirrung, B. **O'Meara**, M. W. Pennell, S. Mirarab,
M. S. Rosenberg, J. P. Balhoff, H. M. Bik, T. A. Heath, P. E.
Midford, J. W. Brown, E. J. McTavish, J. Sukumaran, M. Westneat,
M. E. Alfaro, A. Steele, and G. Jordan (2013i). "Phylotastic!
Making tree-of-life knowledge accessible, reusable and
convenient". In: _BMC Bioinformatics_ 14.1.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013a).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013b).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013c).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013d).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013e).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013f).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013g).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013h).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Soltis, D. E, M. E. Mort, M. Latvis, E. V. Mavrodiev, B. C.
**O'Meara**, P. S. Soltis, J. G. Burleigh, and R. R. de Casas (2013i).
"Phylogenetic relationships and character evolution analysis of
Saxifragales using a supermatrix approach". In: _American Journal
of Botany_ 100.5, pp. 916-929.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013a).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013b).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013c).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013d).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013e).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013f).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013g).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013h).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Hulsey, C. D, B. P. Keck, H. Alamillo, and B. C. **O'Meara** (2013i).
"Mitochondrial genome primers for Lake Malawi cichlids". In:
_Molecular Ecology Resources_ 13.3, pp. 347-353.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013a).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013b).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013c).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013d).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013e).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013f).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013g).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013h).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Beaulieu, J. M, B. C. **O'Meara**, and M. J. Donoghue (2013i).
"Identifying Hidden Rate Changes in the Evolution of a Binary
Morphological Character: The Evolution of Plant Habit in
Campanulid Angiosperms". In: _Systematic Biology_ 62.5, pp.
725-737.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012a). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012b). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012c). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012d). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012e). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012f). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012g). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012h). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Stoltzfus, A, B. **O'Meara**, J. Whitacre, R. Mounce, E. L. Gillespie,
S. Kumar, D. F. Rosauer, and R. A. Vos (2012i). "Sharing and
re-use of phylogenetic trees (and associated data) to facilitate
synthesis". In: _BMC Research Notes_ 5.1.

Smith, S. A. and B. C. **O'Meara** (2012a). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012b). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012c). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012d). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012e). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012f). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012g). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012h). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

Smith, S. A. and B. C. **O'Meara** (2012i). "treePL: divergence time
estimation using penalized likelihood for large phylogenies". In:
_Bioinformatics_ 28.20, pp. 2689-2690.

**O'Meara**, B. C. (2012a). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012b). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012c). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012d). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012e). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012f). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012g). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012h). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

**O'Meara**, B. C. (2012i). "Evolutionary Inferences from Phylogenies:
A Review of Methods". In: _Annual Review of Ecology, Evolution,
and Systematics_ 43.1, pp. 267-285.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012a). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012b). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012c). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012d). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012e). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012f). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012g). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012h). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Beaulieu, J. M, D. Jhwueng, C. Boettiger, and B. C. **O'Meara**
(2012i). "MODELING STABILIZING SELECTION: EXPANDING THE
ORNSTEIN-UHLENBECK MODEL OF ADAPTIVE EVOLUTION". In: _Evolution_
66.8, pp. 2369-2383.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011a). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011b). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011c). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011d). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011e). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011f). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011g). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011h). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Stack, J. C, L. J. Harmon, and B. **O'Meara** (2011i). "RBrownie: an R
package for testing hypotheses about rates of evolutionary
change". In: _Methods in Ecology and Evolution_ 2.6, pp. 660-662.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011a). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011b). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011c). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011d). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011e). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011f). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011g). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011h). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Goff, S. A, M. Vaughn, S. McKay, E. Lyons, A. E. Stapleton, D.
Gessler, N. Matasci, L. Wang, M. Hanlon, A. Lenards, A. Muir, N.
Merchant, S. Lowry, S. Mock, M. Helmke, A. Kubach, M. Narro, N.
Hopkins, D. Micklos, U. Hilgert, M. Gonzales, C. Jordan, E.
Skidmore, R. Dooley, J. Cazes, R. McLay, Z. Lu, S. Pasternak, L.
Koesterke, W. H. Piel, R. Grene, C. Noutsos, K. Gendler, X. Feng,
C. Tang, M. Lent, S. Kim, K. Kvilekval, B. S. Manjunath, V.
Tannen, A. Stamatakis, M. Sanderson, S. M. Welch, K. A. Cranston,
P. Soltis, D. Soltis, B. **O'Meara**, C. Ane, T. Brutnell, D. J.
Kleibenstein, J. W. White, J. Leebens-Mack, M. J. Donoghue, E. P.
Spalding, T. J. Vision, C. R. Myers, D. Lowenthal, B. J. Enquist,
B. Boyle, A. Akoglu, G. Andrews, S. Ram, D. Ware, L. Stein, and D.
Stanzione (2011i). "The iPlant Collaborative: Cyberinfrastructure
for Plant Biology". In: _Frontiers in Plant Science_ 2.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011a). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011b). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011c). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011d). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011e). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011f). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011g). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011h). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

Abercrombie, J. M, B. C. **O'Meara**, A. R. Moffatt, and J. H.
Williams (2011i). "Developmental evolution of flowering plant
pollen tube cell walls: callose synthase (CalS) gene expression
patterns". In: _EvoDevo_ 2.1, p. 14.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010a). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010b). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010c). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010d). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010e). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010f). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010g). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010h). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

COLLAR, D. C, J. A. SCHULTE, B. C. O'MEARA, and J. B. LOSOS
(2010i). "Habitat use affects morphological diversification in
dragon lizards". In: _Journal of Evolutionary Biology_ 23.5, pp.
1033-1049.

Smith, S. A. and B. C. **O'Meara** (2009a). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009b). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009c). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009d). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009e). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009f). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009g). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009h). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

Smith, S. A. and B. C. **O'Meara** (2009i). "Morphogenera, monophyly,
and macroevolution". In: _Proceedings of the National Academy of
Sciences_ 106.36, pp. E97-E98.

**O'Meara**, B. C. (2009a). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009b). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009c). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009d). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009e). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009f). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009g). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009h). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

**O'Meara**, B. C. (2009i). "New Heuristic Methods for Joint Species
Delimitation and Species Tree Inference". In: _Systematic Biology_
59.1, pp. 59-73.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009a). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009b). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009c). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009d). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009e). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009f). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009g). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009h). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

Collar, D. C, B. C. **O'Meara**, P. C. Wainwright, and T. J. Near
(2009i). "PISCIVORY LIMITS DIVERSIFICATION OF FEEDING MORPHOLOGY
IN CENTRARCHID FISHES". In: _Evolution_ 63.6, pp. 1557-1573.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006a). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006b). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006c). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006d). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006e). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006f). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006g). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006h). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

**O'Meara**, B. C, C. A. é, M. J. Sanderson, and P. C. Wainwright
(2006i). "TESTING FOR DIFFERENT RATES OF CONTINUOUS TRAIT
EVOLUTION USING LIKELIHOOD". In: _Evolution_ 60.5, p. 922.

Driskell, A. C. (2004a). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004b). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004c). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004d). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004e). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004f). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004g). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004h). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.

Driskell, A. C. (2004i). "Prospects for Building the Tree of Life
from Large Sequence Databases". In: _Science_ 306.5699, pp.
1172-1174.


## Publications: Books or Book Chapters

Caetano, D, B. **O'Meara**, and J. Beaulieu (2018). "Hidden state
models improve the adequacy of state-dependent diversification
approaches using empirical trees, including biogeographical
models". In: _bioRxiv_.

**O'Meara**, B. C. and J. M. Beaulieu (2014). "Modelling Stabilizing
Selection: The Attraction of Ornstein-Uhlenbeck Models". In:
_Modern Phylogenetic Comparative Methods and Their Application in
Evolutionary Biology: Concepts and Practice_. Ed. by L. Z.
Garamszegi. Berlin, Heidelberg: Springer Berlin Heidelberg, pp.
381-393. ISBN: 978-3-662-43550-2.

Beaulieu, J. M. and B. C. **O'Meara** (2014). "Hidden Markov Models
for Studying the Evolution of Binary Morphological Characters".
In: _Modern Phylogenetic Comparative Methods and Their Application
in Evolutionary Biology: Concepts and Practice_. Ed. by L. Z.
Garamszegi. Berlin, Heidelberg: Springer Berlin Heidelberg, pp.
395-408. ISBN: 978-3-662-43550-2.

**O'Meara**, B. C. (2012). "Phylogenetic Reconstruction". In:
_Encyclopedia of Theoretical Ecology_. Ed. by A. Hastings and L.
Gross. 4. Univ of California Press. ISBN: 0520269659.

**O'Meara**, B. (2008). "PhD Dissertation: Using Trees: Myrmecocystus
Phylogeny and Character Evolution and New Methods for
Investigating Trait Evolution and Species Delimitation". In:
_Nature Precedings_.
