---
layout: page
link: http://www.brianomeara.info/SSB/
slug: SSB
title: SSB candidacy
output:
  html_document:
    includes:
       in_header: GA_Script.html
---

I'm running for Society of Systematic Biologists president in the 2020 election. At the time of agreeing to run, I don't know who the other candidates are -- it's possible they would be better (and I will update this page to link to their information once I learn who they are), so please consider all of us carefully. The president helps set the tone for the society and agrees to participate for three years (president elect, president, and past president, each for a year), though changes also go through the [executive committee](https://www.systbio.org/executive-committee.html) or the broader [council](https://www.systbio.org/council.html). Changes at the Evolution meetings, put on by SSB, the American Society of Naturalists, and the Society for the Study of Evolution together, have to go through the meeting organizers, the meeting committee, or leadership of all three societies. I describe this so people know that my goals below are things I will push for, but I can't guarantee I'll be convincing enough to have all, or even any, go through.

## SSB Contributions

I have served on SSB's council and served as the first ever communications director. I was heavily involved in handling the fallout from issues with a new publishing platform for *Systematic Biology*: associate editors were being listed as authors, articles that people paid to make open access were being put behind paywalls, DOIs were not working, etc. A description of some of my efforts regarding this is [here](https://github.com/systbiol/reports/blob/master/2017_June/Communications.md) -- it included frequent contacts with the people on our publisher's team dealing with issues, contacting affected authors, and even a [script to check for known problems](https://github.com/systbiol/publisherchecking). I also started SSB's committee to talk to other publishers, though final negotiations (which resulted in staying with Oxford, but with better terms) were done by SSB's longtime partners, [Burk and Associates](http://www.burkinc.com/) (who have far more expertise negotiating).

I have been concerned about unwelcome and exclusionary behavior in the field. In response to reports of unwelcome behaviors at Evolution in 2017, I (posting as the Society) created a [qualitative survey](https://twitter.com/systbiol/status/881330667652513793?s=20) to gather suggestions and [reached out](https://twitter.com/systbiol/status/880995237879042049?s=20) to people reporting issues. I then joined the [Code of Conduct committee](https://www.evolutionmeetings.org/general-meeting-information.html#CoCC) for the three evolution societies (SSB, ASN, SSE), which is led by [Andrea Case](https://www.kent.edu/biology/profile/andrea-l-case). That committee has crafted and gotten adopted [policies on enforcement](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/reporting.pdf) of our code of conduct (with feedback from leadership of the three societies), started the [Evo Allies program](https://www.evolutionmeetings.org/safe-evolution.html), created an IRB-approved survey of Evolution attendees, presented results of that survey ([O'Meara et al. 2019](https://figshare.com/articles/Unwelcome_behaviors_at_the_Evolution_meetings_Survey_results/8311595)), and written transparency reports ([2017 & 2018](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/transparency_report.pdf), [2019](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/transparency_report__2019.pdf)) so people can see what is happening and potential areas to improve.

## Goals

If you were to ask biologists, SSB’s selling points are that it puts out a great journal with a harrowingly thorough review process, organizes a wonderful standalone meeting, and contributes to a successful joint Evolution meeting; members receive discounts on all these, and some may be eligible for awards for talks or research. These all represent a tremendous amount of largely volunteer effort, and it’s a testament to the society that these have continued to thrive and even expand. It’s essential to support and nurture these aspects.

However, SSB is more than these: it’s a **Society** of **Systematic Biologists**. We’re a community of people with a shared passion for solving questions using systematics. We need to take steps to knit this community together and have members benefit from these interactions. Some goals I would seek to achieve:

**Mentoring across institutions**: while many institutions are creating mentoring relationships internally, internal power dynamics can still affect how well those work (how honest can an assistant professor be about their concerns about staying in academia to someone who will be voting on their tenure in a couple of years, for example?). A unique aspect of scientific societies is that their membership spans career paths, career stages, and institutions. I would create a system where people could form connections and meet virtually a few times a year, in pairs or small groups, to discuss science, career questions, and more. Importantly, information flow would not be unidirectional -- someone with more experience in academia could explore concerns with promotion with a junior colleague, but also learn about new areas of synthesis between ecology and evolution from them, for example.

**Support joint efforts**: Whether it’s support for standards for data types or deposition requirements, areas of interest for grant agencies, or initiatives to get rid of structural barriers that push out people, a society can provide a framework so that it is not a single person working on their own but a collective effort with our membership’s backing. This makes the efforts more likely to succeed but also more likely to be sustained as new people rotate in to continue them.

**Make our society a welcoming, safe place**: SSB has no requirements that members behave ethically, nor any guarantees that members won’t see their harasser at the next SSB event no matter how egregious and well-documented the bad behavior. The Code of Conduct helps address this at meetings, and there are efforts to make a Code of Ethics governing behavior in general, but those are still under development, and there are many more ways we can improve.
