---
title: U. Minnesota EEB Head
---

In Feb. 2020 I applied for a [position as department head](https://cbs.umn.edu/blogs/cbs-connect/ecology-evolution-and-behavior-seeking-department-head-candidates) for the University of Minnesota Ecology, Evolution, and Behavior Department. I have made it to the interview stage in Sept. 2020. Here is information and materials relevant to my application. You may be interested in my [CV](http://brianomeara.info/cv.html) and [people who have been through my lab](http://brianomeara.info/personnel.html).

## Science talk

[Slides (large PDF)](https://drive.google.com/file/d/1GOQ7Xw11LwN3MMWoUMoMJMNEQcIEmUnn/view)

<iframe width="560" height="315" src="https://www.youtube.com/embed/BvUwQZo_FGM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### Links from talk


#### Recent papers mentioned

* [Nguyen et al. 2020](https://doi.org/10.1177/1176934319899384): description of the Phylotastic project to make the tree of life more available. See [https://phylotastic.org/](https://phylotastic.org/), including the [results of our teacher workshop](https://jwiggi18.github.io/phyloEd/)
* [Landerer et al. 2020](https://doi.org/10.1186/s12862-020-01649-w): understanding transfer of part of a chromosome in yeast
* [Cope et al. 2020](https://doi.org/10.1186/s12864-020-6761-3): using phylogenies to infer gene coevolution
* [Meireles et al. 2020](https://doi.org/10.1111/nph.16771): leaf reflectance to capture plant evolutionary history. Also see [https://www.spectralbiology.org/](https://www.spectralbiology.org/), the new $12.5M center to study spectral biology, headed up by UMN Professor Jeannine Cavender-Bares (note that I have no connection to the center -- it's just a great thing that recently started up)
* [McGee, Borstein, et al. 2020](https://doi.org/10.1038/s41586-020-2652-7): cichlid evolution, including the possible evidence for and impact of hybridization
* [Jhwueng & O'Meara 2020](https://doi.org/10.1177/1176934320901721): paper on numerical properties of phylogenetic tree matrices (which affects precision of parameter estimates)


#### Floral evolution project

* [O'Meara, Smith, et al. 2016](https://doi.org/10.1098/rspb.2015.2304): paper on floral evolution. Note that it has two co-lead authors and two co-senior authors (Fenster and Diggle)
* [NESCent project page](https://nescent.org/science/awards_summary.php-id=90.html)


#### PHRAPL

* [Jackson et al. 2017](https://doi.org/10.1093/sysbio/syx001): basic PHRAPL phylogeographic model
* [Carstens et al. 2017](https://doi.org/10.1016/j.ympev.2017.08.018): analyzing the choices biologists make in models
* [Morales et al. 2017](https://doi.org/10.1093/sysbio/syw100): empirical case of speciation with gene flow in *Myotis* 
* [Jackson et al. 2017](https://doi.org/10.1093/sysbio/syw117): species delimitation using PHRAPL


#### Protein and UCE model

* [Beaulieu et al. 2020](https://www.biorxiv.org/content/10.1101/2020.05.12.091744v2): preprint on ultraconserved elements model
* [Beaulieu et al. 2019](https://doi.org/10.1093/molbev/msy222): core model for protein evolution


#### Hidden Side

* [Caetano et al. 2018](10.1111/evo.13602): biogeographic model
* [O'Meara & Beaulieu 2016](https://doi.org/10.3732/ajb.1600012): overview of state-dependent diversification models
* [Beaulieu & O'Meara 2016](https://doi.org/10.1093/sysbio/syw022): hidden state diversification model
* [Beaulieu et al. 2013](https://doi.org/10.1093/sysbio/syt034): hidden model for binary trait transitions


#### Relevant software

* [hisse](https://cran.r-project.org/web/packages/hisse/index.html): diversification models with hidden states
* [PHRAPL](http://www.phrapl.org/): phylogeography model
* [corhmm](https://cran.r-project.org/web/packages/corHMM/index.html): hidden state trait model
* [selac/selon](https://cran.r-project.org/web/packages/selac/index.html): amino acid / UCE model

See my [CV](http://brianomeara.info/cv.html) for more on publications and software.


<hr />


## Leadership talk

[Slides (large PDF)](https://drive.google.com/file/d/1Bvurhw4qnzfQppVGFYi7s4KXzNkPVzCk/view)


<iframe width="560" height="315" src="https://www.youtube.com/embed/LfXevYdz_s0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>




### General links from talk

* [Safe Evolution](https://www.evolutionmeetings.org/safe-evolution.html), especially the [poster](https://figshare.com/articles/Unwelcome_behaviors_at_the_Evolution_meetings_Survey_results/8311595), and transparency reports for [2017-2018](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/transparency_report.pdf) and [2019](https://www.evolutionmeetings.org/uploads/4/8/8/0/48804503/transparency_report__2019.pdf)
* [Academic Misconduct Database](https://academic-sexual-misconduct-database.org/): Created initially by Julie Libarkin, tracks publicly resolved and ongoing cases of sexual misconduct perpetrated by U.S. faculty, administrators and other staff. See [here](https://academic-sexual-misconduct-database.org/incidents?query=Minnesota) for Minnesota cases.
* [Better Letter](http://brianomeara.info/better-letter.html): Resource I made to make it easier to look for biases in letters of rec 
* Teaching: My senior level [macroevolution class](http://brianomeara.info/eeb464.html) and [graduate course in phylogenetics](http://phylometh.info/)
* [UTK EEB Community of Practice](https://eeb.utk.edu/eeb-community-of-practice/): how we are ensuring labs can open safely while respecting the needs of everyone inside them
* [NSF Survey of Earned Doctorates](https://www.nsf.gov/statistics/srvydoctorates/): PhDs by various categories per year
* [NSF Awards Advanced Search](https://www.nsf.gov/awardsearch/advancedSearch.jsp): to look up awarded funding
* [scholar R package](https://github.com/jkeirstead/scholar): for pulling publication information from Google Scholar


### UMN-specific links

* ["Racism with a smile"](https://www.nytimes.com/2020/06/01/us/minneapolis-racism-minnesota.html): *New York Times* article on racism in Minneapolis following the attention garnered by George Floyd's murder
* [Bias Reponse Referral Network](https://bias-response.umn.edu/): reporting incidents of bias, includes transparency reports of how past incidents were handled
* [UMN Aurora Center for Advocacy & Education](http://aurora.umn.edu/get-help): help all victims/survivors/concerned people of sexual assault, relationship violence, stalking, and sexual harassment, including information on [reporting options](http://aurora.umn.edu/get-help/reporting-options)
* [Ureport](https://compliance.umn.edu/report): to report misconduct in general. Includes an anonymous reporting option. Also see [https://onestop.umn.edu/terms-and-conditions/student-complaints-and-grievances](https://onestop.umn.edu/terms-and-conditions/student-complaints-and-grievances) for additional options open to students (and others, in some cases).
* [*StarTribune* article on grad students confronting racism](https://www.startribune.com/at-university-of-minnesota-students-pressure-faculty-to-confront-racism-in-academia/571908082/), including the actions of UMN EEB students and faculty response
* [Student Ombuds](https://sos.dl.umn.edu/ombuds): confidential resource for students to help resolve any university-related conflict or concern
* [Crisis services](https://counseling.umn.edu/crisis-services): includes crisis line, 612-301-4673
* [Self-Help](https://counseling.umn.edu/self-help): anonymous mental health screenings, alcohol assessment, and more
* [Student Counseling](https://counseling.umn.edu/): Individual and group therapy and more
* [BIPOC Mental Health Collective](https://counseling.umn.edu/bipoc-mental-health-collective): meets second Thursday of each month
* [Employee Assistance Program](https://humanresources.umn.edu/benefits/employee-assistance): confidential consulting on mental health, relationships, stress, and more


### References from talk

* [Boring 2017](https://doi.org/10.1016/j.jpubeco.2016.11.006): Gender biases in student evaluations of teaching
* [Bosshardt & Watts 2001](https://doi.org/10.1080/00220480109595166): Comparing Student and Instructor Evaluations of Teaching
* [Hofstra et al. 2020](https://doi.org/10.1073/pnas.1915378117): The diversity-innovation paradox in science
* [MacNell et al. 2015](https://doi.org/10.1007/s10755-014-9313-4): What’s in a Name: Exposing Gender Bias in Student Ratings of Teaching
* [McLeod & Lobel 1992](https://journals.aom.org/doi/pdf/10.5465/ambpp.1992.17515639): The effects of ethnic diversity on idea generation in small groups
* [McLeod et al. 1996](https://journals.sagepub.com/doi/10.1177/1046496496272003): Ethnic diversity and creativity in small groups
* [Nielsen et al. 2017](https://doi.org/10.1073/pnas.1700616114): Opinion: Gender diversity leads to better science
* [Nikaj et al. 2018](https://faseb.onlinelibrary.wiley.com/doi/epdf/10.1096/fj.201800639): Examining trends in the diversity of the US National Institutes of Health participating and funded workforce
* [O'Meara et al. 2019](https://figshare.com/articles/Unwelcome_behaviors_at_the_Evolution_meetings_Survey_results/8311595): Unwelcome behaviors at the Evolution meetings: Survey results
* [Russ et al. 2002](https://doi.org/10.1080/03634520216516): Coming out in the classroom... An occupational hazard? The influence of sexual orientation on teacher credibility and perceived student learning. 

