---
title: "Course ads on R-sig-phylo"
description: "The main mailing list for phylogenetics in R, R-sig-phylo, is now nearly all ads for courses from a small set of companies. It would be great if they stopped this."
author: "Brian O'Meara"
date: "07/18/2025"
citation: true
categories: [Rstats] 
---

The R project maintains [special interest mailing lists](https://www.r-project.org/mail.html): using R in ecology, using R in phylogenetics, etc.:

> Additionally, there are several specific Special Interest Group (=: SIG) mailing lists; however do post to only one list at time (‘SIG’ or general one), cross-posting is considered to be impolite.

The phylogenetics one has been a good place for discussion and learning; I even quote posts from it at length in the [help for ancestral state reconstruction](https://thej022214.github.io/OUwie/reference/OUwie.anc.html#details-1) using Ornstein-Uhlenbeck models in the OUwie documentation, as Joe Felsenstein, Dave Bapst, Simone Blomberg, Marguerite Butler, Nick Matzke, and Thomas Hansen all weighed in (I wrote the function so that by default it gives an error until a user indicates they actually read the documentation about the risks of this analysis).

However, lately the list is filled with posts for courses in R. It might not be unreasonable: a workshop in R for phylogenetics, like the [evolutionary quantitative genetics workshop](https://eqgw.github.io/index.html) led by community members Josef Uyeda and Fabio Machado, could be appropriately sent to the list. But now the list nearly *all* ads for courses, most of which do not relate to phylogenetics. Out of the last 50 [threads](https://www.mail-archive.com/r-sig-phylo@r-project.org/index.html) on the list (Feb 2025-July 2025):

* 22 were by Carlo Pecoraro of Physalia Courses
* 9 were by Oliver Hooker of PR Statistics
* 8 were by Soledad De Esteban-Trivigno of Transmitting Science 

Nearly all of these were for paid courses offered by these groups.

There were also two (2!) threads with actual questions on R in phylogenetics (only one of which had answers), a request to nominate scientists for a medal, and two posts from the long-serving volunteer list moderator, Hilmar Lapp, about proper conduct, including [one about too many training course advertisements](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg06067.html). Hilmar's request was that groups post no more than two courses a month and only post each course once (no "last chance of" or similar follow-ups). All the companies above violated this (links to examples): [Physalia](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg06092.html) (which also posts over 3.5 courses per month), [PR Statistics](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg06082.html), and [Transmitting Science](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg06106.html).

An easy criticism would be to argue for different moderation choices or actions, but any such move puts even more work on a long-serving community member. Why should someone volunteer their time to play whack-a-mole with multiple people who are paid to send out announcements as part of their day job? It's not sustainable. It would be better if companies decided to be responsible and respect listserv rules (including the R-project's request not to cross-post). They could even start their own R-sig listserv of courses that people could opt into -- there's a need for quality R courses, after all.

Use of mailing lists just to sell courses is even worse outside R-sig-phylo -- for example, in June the [28 threads in the R-sig-ecology list](https://stat.ethz.ch/pipermail/r-sig-ecology/2025-June/thread.html) were ALL for courses (11 from Physalia, 8 from PR Statistics, 6 from the Institute for Statistical and Data Science, 2 from Transmitting Science, 1 from Highland Statistics), despite the huge number of R users in ecology, and the trend is continuing in July.

Email discussion lists are definitely declining (you can see looking through the R special interest lists how many are practically abandoned) -- we all get too many emails, and in some ways social media has replaced the need for mailing lists to ask questions and get answers (see `#rstats` on bluesky, for example). But one could imagine that in the coming era of AI slop, mailing lists with responses limited to those written by actual humans would once more become essential. It's sad to see something like R-sig-phylo, which has been a place for good discussion and could be again, get overwhelmed by companies choosing to use it to sell courses: who wants to join or stay on a list if only 4% of posts are directly connected to the list topic? I myself was considering unsubscribing this morning -- thus this plea for things to change (and I might as an intermediate step just block any mail from particular companies).

___

To subscribe, go to <https://brianomeara.info/blog.xml> in an RSS reader.